import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {JSDOM} from 'jsdom';
const temp=mkdtempSync(path.join(tmpdir(),'gi-i3-'));
Object.assign(process.env,{GAMEINDEX_DB:path.join(temp,'qa.sqlite'),GAMEINDEX_DATA_DIR:temp,DATABASE_URL:'',GAMEINDEX_DATABASE_URL:'',GAMEINDEX_TARGET_SCHEMA:'47',NODE_ENV:'test',OLLAMA_ENABLED:'false',GAMEINDEX_BACKGROUND_WORKERS:'false'});
for(const key of ['RENDER','RENDER_SERVICE_ID','RENDER_EXTERNAL_HOSTNAME','WEBSITE_SITE_NAME','WEBSITE_INSTANCE_ID','WEBSITE_HOSTNAME'])delete process.env[key];
const {initializeDatabase}=await import('../src/database/seed.mjs');
const {db,transaction}=await import('../src/database/connection.mjs');
const {registerDeliveryRelease}=await import('../src/database/delivery-release.mjs');
const {installQualityContent}=await import('../src/database/quality-content-0992-i3.mjs');
const {listGames,getGameBySlug}=await import('../src/database/repositories/game-repository.mjs');
const {publicDexterConsult,resolveDexterGame}=await import('../src/dexter/public-consult.mjs');
const {gamePublicVisual}=await import('../src/images/public-visual.mjs');
const {setGameMedia,setExperienceMedia,gameMediaProfile}=await import('../src/images/game-media-service.mjs');
const {resolvePersonalization}=await import('../src/personalization/personalization-service.mjs');
const {redactTechnicalPayload,safePublicError}=await import('../src/api/public-boundary.mjs');
let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS',name);}
try{
 initializeDatabase();
 await test('I3 upgrades once and repeated startup makes zero changes',()=>{assert.equal(db.prepare("SELECT value FROM meta WHERE key='runtime_release'").get().value,'BETA_0_992_I3_PRODUCT_QUALITY');const before=db.prepare('SELECT total_changes() n').get().n;registerDeliveryRelease();registerDeliveryRelease();assert.equal(db.prepare('SELECT total_changes() n').get().n,before);});
 await test('nested transaction failure rolls back the complete unit',()=>{assert.throws(()=>transaction(()=>{db.prepare("INSERT INTO meta VALUES('i3_outer','1')").run();transaction(()=>db.prepare("INSERT INTO meta VALUES('i3_inner','1')").run());throw new Error('rollback');}),/rollback/);assert.equal(db.prepare("SELECT count(*) n FROM meta WHERE key IN ('i3_inner','i3_outer')").get().n,0);transaction(()=>{try{transaction(()=>{db.prepare("INSERT INTO meta VALUES('i3_failed_inner','1')").run();throw new Error('inner');});}catch{}db.prepare("INSERT INTO meta VALUES('i3_ok_outer','1')").run();});assert.ok(db.prepare("SELECT 1 FROM meta WHERE key='i3_ok_outer'").get());assert.equal(db.prepare("SELECT 1 FROM meta WHERE key='i3_failed_inner'").get(),undefined);});
 await test('RDR2 is distinct; GTA III history remains unlisted; nearby GTA games remain public',()=>{const rdr=getGameBySlug('red-dead-redemption-2'),gta=getGameBySlug('grand-theft-auto-iii');assert.ok(rdr&&gta&&rdr.id!==gta.id);assert.equal(gta.visibility,'UNLISTED');assert.ok(!listGames({includeDrafts:false}).some(g=>g.id===gta.id));for(const slug of ['grand-theft-auto-iv','grand-theft-auto-v','grand-theft-auto-vi'])assert.ok(listGames({includeDrafts:false}).some(g=>g.slug===slug));assert.match(gamePublicVisual(rdr).cover,/red-dead-redemption-2/);assert.ok(!JSON.stringify(rdr).includes('Liberty City'));});
 await test('avatar IDs survive; custom assets are preserved on reinstall',()=>{const rows=db.prepare("SELECT * FROM profile_avatar_catalog WHERE built_in=1 AND enabled=1").all();assert.equal(rows.length,25);assert.equal(new Set(rows.map(r=>readFileSync(new URL('../public'+r.asset_url,import.meta.url),'utf8'))).size,25);const id=rows[0].id;db.prepare("UPDATE profile_avatar_catalog SET asset_url='/custom/manual.svg' WHERE id=?").run(id);db.prepare("DELETE FROM meta WHERE key='content_0992_i3'").run();installQualityContent();assert.equal(db.prepare('SELECT asset_url FROM profile_avatar_catalog WHERE id=?').get(id).asset_url,'/custom/manual.svg');});
 await test('cover framing reaches both catalog and game; logo never overwrites cover',()=>{const g=getGameBySlug('red-dead-redemption-2');const image='data:image/jpeg;base64,'+readFileSync(new URL('../public/assets/games/red-dead-redemption-2.jpg',import.meta.url)).toString('base64');const cover=setGameMedia({gameId:g.id,slotKey:'COVER',imageDataUrl:image,fitMode:'CONTAIN'});assert.equal(gamePublicVisual(g).presentation.fitMode,'CONTAIN');assert.equal(resolvePersonalization({game:g}).resolved.media.logo.slot,'COVER');const logo=setExperienceMedia({gameId:g.id,experienceKey:'main',slotKey:'LOGO',imageDataUrl:image,fitMode:'CONTAIN'});assert.equal(gameMediaProfile(g.id,'COVER').imageUrl,cover.imageUrl);const p=resolvePersonalization({game:g});assert.equal(p.resolved.media.logo.imageUrl,logo.imageUrl);assert.equal(p.resolved.media.logo.slot,'LOGO');});
 await test('Dexter resolves aliases, compound catalog questions and working action routes offline',async()=>{assert.equal(resolveDexterGame('Quem desenvolveu RDR2?').game.slug,'red-dead-redemption-2');const r=await publicDexterConsult({question:'Quem desenvolveu RDR2 e em quais plataformas posso jogar?',allowResearch:false,conversationId:'i3_conversation',contextScope:'local_owner'});assert.match(r.answer.directAnswer,/Rockstar Games/);assert.ok(r.answer.details.some(x=>x.includes('PlayStation 4')));assert.equal(r.answer.researched,false);assert.ok(r.answer.actions[0].href.includes('?slug='));const next=await publicDexterConsult({question:'E o lançamento?',allowResearch:false,conversationId:'i3_conversation',contextScope:'local_owner'});assert.match(next.answer.directAnswer,/2018/);const outsider=await publicDexterConsult({question:'E o lançamento?',allowResearch:false,conversationId:'i3_conversation',contextScope:'different_owner'});assert.equal(outsider.answer.game,null);});
 await test('Dexter product actions respect server capabilities and never pretend to execute writes',async()=>{const denied=await publicDexterConsult({question:'Como usar o Image Manager?',capabilities:[],allowResearch:false});assert.ok(!denied.answer.actions.some(a=>a.href.includes('image-library')));const allowed=await publicDexterConsult({question:'Como usar o Image Manager?',capabilities:['image_management'],allowResearch:false});assert.equal(allowed.answer.actions[0].href,'/image-library.html');assert.match(allowed.answer.directAnswer,/salve/i);});
 await test('unverified current claims are not invented when research is disabled',async()=>{const r=await publicDexterConsult({question:'Quais os novos códigos de Minecraft hoje?',allowResearch:false});assert.equal(r.answer.confidence,0);assert.equal(r.answer.canRetry,true);assert.match(r.answer.directAnswer,/mudado|confirmar/);});
 await test('public errors and structured diagnostics do not leak hidden reasoning or secrets',()=>{assert.ok(!safePublicError('SQLITE no such table sessions').includes('SQLITE'));assert.deepEqual(redactTechnicalPayload({feature:'test',output:{password:'secret',systemPrompt:'hidden',chainOfThought:'private',status:'ok'}}),{feature:'test',output:{status:'ok'}});});
 await test('live translation handles dynamic nodes, attributes, user text, round trip and reduced motion',async()=>{const dom=new JSDOM('<html><head><title>Configurações | GameIndex</title></head><body><h1>Configurações</h1><button aria-label="Abrir perfil">Salvar</button><input placeholder="Pesquisar jogos..."><p translate="no">Salvar</p><div id="dynamic"></div></body></html>',{url:'https://test.local',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.matchMedia=()=>({matches:true});w.fetch=async url=>({ok:true,json:async()=>JSON.parse(readFileSync(new URL('../public'+url.split('?')[0],import.meta.url),'utf8'))});w.eval(readFileSync(new URL('../public/js/localization-0992-i3.js',import.meta.url),'utf8'));await new Promise(r=>setTimeout(r,10));await w.GII18n.set('en-US');assert.equal(w.document.querySelector('h1').textContent,'Settings');assert.equal(w.document.querySelector('button').getAttribute('aria-label'),'Open profile');assert.equal(w.document.querySelector('input').placeholder,'Search games...');assert.equal(w.document.querySelector('[translate=no]').textContent,'Salvar');w.document.getElementById('dynamic').innerHTML='<button>Cancelar</button>';await new Promise(r=>setTimeout(r,45));assert.equal(w.document.getElementById('dynamic').textContent,'Cancel');await w.GII18n.set('es-ES',{animate:true});assert.equal(w.document.querySelector('h1').textContent,'Configuración');assert.equal(w.document.querySelector('.gi-language-transition').dataset.reduced,'true');assert.ok(w.document.querySelector('.gi-language-transition img').src.endsWith('/es.svg'));await w.GII18n.set('pt-BR');assert.equal(w.document.querySelector('h1').textContent,'Configurações');assert.equal(w.document.getElementById('dynamic').textContent,'Cancelar');await Promise.all([w.GII18n.set('en-US'),w.GII18n.set('es-ES')]);assert.equal(w.GII18n.language,'es-ES');dom.window.close();});
 console.log(JSON.stringify({ok:true,release:'0.992 I3',passed}));
}finally{db.close();rmSync(temp,{recursive:true,force:true});}
