import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import net from 'node:net';
import dns from 'node:dns/promises';
import {JSDOM,VirtualConsole} from 'jsdom';
const root=path.resolve(import.meta.dirname,'..'),temp=mkdtempSync(path.join(tmpdir(),'gi-i1-'));
Object.assign(process.env,{GAMEINDEX_DB:path.join(temp,'test.sqlite'),GAMEINDEX_DATA_DIR:temp,DATABASE_URL:'',GAMEINDEX_DATABASE_URL:'',GAMEINDEX_TARGET_SCHEMA:'47',NODE_ENV:'test',GAMEINDEX_BACKGROUND_WORKERS:'false',GAMEVAULT_AUTOGEN_ENABLED:'false',OLLAMA_ENABLED:'false'});
for(const k of ['RENDER','RENDER_SERVICE_ID','RENDER_EXTERNAL_HOSTNAME','WEBSITE_SITE_NAME','WEBSITE_INSTANCE_ID','WEBSITE_HOSTNAME'])delete process.env[k];
const {initializeDatabase}=await import('../src/database/seed.mjs');initializeDatabase();
const {db}=await import('../src/database/connection.mjs');
const {getGameBySlug}=await import('../src/database/repositories/game-repository.mjs');
const {publicDexterConsult,resolveDexterGame}=await import('../src/dexter/public-consult.mjs');
const {upsertKnowledge}=await import('../src/database/repositories/knowledge-repository.mjs');
const {upsertSource}=await import('../src/database/repositories/source-repository.mjs');
const {registerResearchSource,registeredSources}=await import('../src/research/registered-sources.mjs');
const {installIdentityCatalog}=await import('../src/users/avatar-catalog-0992-i1.mjs');
let count=0,child;const oldFetch=globalThis.fetch,oldLookup=dns.lookup;
const test=async(name,fn)=>{await fn();count++;console.log('PASS',name);};
const wait=async(fn)=>{for(let i=0;i<150;i++){if(await fn())return;await new Promise(r=>setTimeout(r,30));}throw new Error('Timed out waiting for UI');};
try{
 await test('five enabled non-placeholder vector avatars per role; install is idempotent',()=>{installIdentityCatalog();installIdentityCatalog();for(const role of ['FREE','PRO','TESTER','DEV','CREATOR']){const rows=db.prepare('SELECT * FROM profile_avatar_catalog WHERE class=? AND enabled=1 AND built_in=1').all(role);assert.equal(rows.length,5,role);const files=rows.map(r=>{assert.equal(r.placeholder,0);return readFileSync(path.join(root,'public',r.asset_url),'utf8');});assert.equal(new Set(files).size,5);}});
 const game=getGameBySlug('blox-fruits'),source=upsertSource({url:'https://fixture-wiki.test/wiki/Blox_Fruits',title:'Synthetic test source',quality:.95});
 const fact='Blox Fruits progression fixture: players explore islands and unlock abilities.';
 upsertKnowledge({gameId:game.id,title:'Blox Fruits progression',summary:'Blox Fruits progression islands abilities',confidence:.95,verifiedAt:new Date().toISOString(),topics:['progression'],claims:[{text:fact,sourceIds:[source.id],confidence:.95}]});
 await test('Dexter hydrates verified claims, gives source and preserves Experience parent',async()=>{const r=await publicDexterConsult({question:'Blox Fruits progression',conversationId:'conversation_test',contextScope:'owner-a'});assert.equal(r.answer.game.slug,'blox-fruits');assert.equal(r.answer.game.parent.slug,'roblox');assert.ok([r.answer.directAnswer,...r.answer.details].includes(fact));assert.ok(r.answer.sources.some(s=>s.url===source.url));assert.equal(r.answer.researched,false);});
 await test('follow-up context is scoped to its owner and resolves explicit game overrides',async()=>{const r=await publicDexterConsult({question:'E progression?',conversationId:'conversation_test',contextScope:'owner-a'});assert.equal(r.answer.game.slug,'blox-fruits');assert.equal(r.diagnostics.continuing,true);const stranger=await publicDexterConsult({question:'E progression?',conversationId:'conversation_test',contextScope:'owner-b'});assert.equal(stranger.answer.game,null);assert.equal(resolveDexterGame('Minecraft progression','blox-fruits').game.slug,'minecraft');});
 await test('expired and invalid freshness timestamps cannot supply a current answer',async()=>{db.prepare("UPDATE knowledge SET verified_at='not-a-date',valid_until='2000-01-01' WHERE game_id=?").run(game.id);globalThis.fetch=async()=>{throw new Error('Synthetic offline');};const r=await publicDexterConsult({question:'Blox Fruits progression atual'});assert.equal(r.memory.count,0);assert.equal(r.answer.canRetry,true);assert.ok(!JSON.stringify(r.answer).includes(fact));globalThis.fetch=oldFetch;});
 await test('wiki recovery validates public addresses and saves additional sources once',async()=>{await assert.rejects(registerResearchSource(game.id,'https://127.0.0.1/wiki/Game'));dns.lookup=async()=>[{address:'93.184.216.34',family:4}];await assert.rejects(registerResearchSource(game.id,'https://example.test/not-a-wiki'));await registerResearchSource(game.id,'https://fixture-wiki.test/wiki/Blox_Fruits');await registerResearchSource(game.id,'https://fixture-wiki.test/wiki/Blox_Fruits');assert.equal(registeredSources(game.id).length,1);dns.lookup=oldLookup;});
 await test('storage-disabled browser still initializes safe theme preferences',()=>{const dom=new JSDOM('<html><body></body></html>',{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;Object.defineProperty(w,'localStorage',{get(){throw new Error('Denied');}});Object.defineProperty(w,'sessionStorage',{get(){throw new Error('Denied');}});w.matchMedia=()=>({matches:false});w.eval(readFileSync(path.join(root,'public/js/theme-bootstrap.js'),'utf8'));w.GIStorage.local.setItem('test','value');assert.equal(w.GIStorage.local.getItem('test'),'value');dom.window.close();});

 await test('automatic upsert preserves manual page, tab and section content',async()=>{const {upsertUniversePage,upsertUniverseTab,upsertUniverseSection}=await import('../src/universe/universe-structure-service.mjs');const page=upsertUniversePage({entityGameId:game.id,canonicalKey:'I1_MANUAL',title:'Manual page',ownership:'MANUAL'});const tab=upsertUniverseTab({entityGameId:game.id,pageId:page.id,canonicalKey:'I1_TAB',title:'Manual tab',ownership:'MANUAL'});const section=upsertUniverseSection({entityGameId:game.id,pageId:page.id,tabId:tab.id,canonicalKey:'I1_SECTION',title:'Manual section',content:{text:'Do not replace'},ownership:'MANUAL'});upsertUniversePage({entityGameId:game.id,canonicalKey:'I1_MANUAL',title:'Automatic'});upsertUniverseTab({entityGameId:game.id,pageId:page.id,canonicalKey:'I1_TAB',title:'Automatic'});upsertUniverseSection({entityGameId:game.id,pageId:page.id,tabId:tab.id,canonicalKey:'I1_SECTION',title:'Automatic',content:{text:'Replacement'}});assert.match(db.prepare('SELECT title_json FROM universe_pages WHERE id=?').get(page.id).title_json,/Manual page/);assert.match(db.prepare('SELECT title_json FROM universe_tabs WHERE id=?').get(tab.id).title_json,/Manual tab/);assert.match(db.prepare('SELECT content_json FROM universe_sections WHERE id=?').get(section.id).content_json,/Do not replace/);});
 const port=await new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});}),base='http://127.0.0.1:'+port;
 child=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:String(port),GAMEINDEX_STARTUP_VISUAL_SCAN:'false',GAMEINDEX_IMAGE_REPAIR_WORKER:'false',GAMEINDEX_CONSTRUCTION_ENABLED:'false',GAMEINDEX_FULL_BUILD_ENABLED:'false'},stdio:'ignore'});
 await wait(async()=>{try{return (await fetch(base+'/api/health')).ok;}catch{return false;}});
 await test('real login form: invalid fields, registration, wrong password, relogin and session',async()=>{let cookie='',requests=0;const errors=[],virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',e=>{if(!e.message.includes('navigation'))errors.push(e.message);});const dom=new JSDOM(await(await fetch(base+'/login.html')).text(),{url:base+'/login.html',runScripts:'outside-only',virtualConsole}),w=dom.window;w.AbortController=AbortController;w.GV={safe:s=>String(s).replace(/[&<>"']/g,'')};w.fetch=async(url,options={})=>{if(options.method==='POST')requests++;const r=await fetch(new URL(url,base),{...options,headers:{...options.headers,cookie}});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return r;};await new Promise(r=>w.setTimeout(r,0));w.eval(readFileSync(path.join(root,'public/js/auth.js'),'utf8'));const $=id=>w.document.getElementById(id);assert.equal($('username').disabled,true);$('authSubmit').click();assert.equal(requests,0);assert.match($('authMessage').textContent,/Confira/);w.document.querySelector('[data-auth-mode="register"]').click();$('username').value='i1_dom_user';$('displayName').value='DOM User';$('email').value='i1-dom@example.test';$('password').value='test-password-123';$('authSubmit').click();assert.equal($('authSubmit').disabled,true);await wait(()=>$('authSubmit').disabled===false);assert.equal((await(await w.fetch('/api/auth/me')).json()).authenticated,true);await w.fetch('/api/auth/logout',{method:'POST'});w.document.querySelector('[data-auth-mode="login"]').click();$('password').value='wrong-password';$('authSubmit').click();await wait(()=>$('authSubmit').disabled===false);assert.equal((await(await w.fetch('/api/auth/me')).json()).authenticated,false);assert.notEqual($('authMessage').textContent,'Processando...');$('password').value='test-password-123';$('authSubmit').click();await wait(()=>$('authSubmit').disabled===false);assert.equal((await(await w.fetch('/api/auth/me')).json()).authenticated,true);assert.deepEqual(errors,[]);dom.window.close();});

 await test('draft games are not exposed by public universe endpoints',async()=>{const draft=getGameBySlug('minecraft');db.prepare("UPDATE games SET status='DRAFT' WHERE id=?").run(draft.id);for(const route of ['universe-099','identity-099','technical-099','experiences-099'])assert.equal((await fetch(base+'/api/games/minecraft/'+route)).status,404,route);});
 console.log(JSON.stringify({ok:true,passed:count,visualRendering:false}));
}finally{globalThis.fetch=oldFetch;dns.lookup=oldLookup;if(child&&child.exitCode===null){const exited=new Promise(r=>child.once('exit',r));child.kill('SIGTERM');await exited;}db.close();rmSync(temp,{recursive:true,force:true});}
