import { randomBytes, randomUUID, createHash } from "node:crypto";
import { db, json, nowIso, parseJson, transaction } from "../database/connection.mjs";
import { accessSnapshotForUser } from "../access/capability-service.mjs";

const FEEDBACK_CATEGORIES=new Set(["INCORRECT_FACT","WEAK_SOURCE","UNCLEAR_TEXT","MISSING_DETAIL","BROKEN_LINK","BROKEN_IMAGE","MOBILE_LAYOUT","ACCESSIBILITY","PERFORMANCE","OTHER"]);
function clean(value,max=1000){return String(value||"").normalize("NFKC").replace(/<[^>]*>/g," ").replace(/[\u0000-\u001f]/g," ").replace(/\s+/g," ").trim().slice(0,max);}
function mapCampaign(row){if(!row)return null;return {id:row.id,gameId:row.game_id,constructionRunId:row.construction_run_id,title:row.title,description:row.description,checklist:parseJson(row.checklist_json,[]),status:row.status,createdBy:row.created_by,createdAt:row.created_at,updatedAt:row.updated_at};}
function mapFeedback(row){return row?{id:row.id,campaignId:row.campaign_id,testerUserId:row.tester_user_id,pageId:row.page_id,pageVersionId:row.page_version_id,constructionRunId:row.construction_run_id,category:row.category,title:row.title,description:row.description,status:row.status,developerResponse:row.developer_response,createdAt:row.created_at,updatedAt:row.updated_at}:null;}

export function createTesterInvitation({actorUserId,targetUserId=null,emailHint="",expiresHours=72}={}){if(targetUserId&&!db.prepare(`SELECT id FROM users WHERE id=?`).get(targetUserId))throw new Error("Usuário não encontrado.");const token=randomBytes(24).toString("base64url"),id=randomUUID(),now=nowIso(),expiresAt=new Date(Date.now()+Math.max(1,Math.min(336,Number(expiresHours)||72))*3600000).toISOString();db.prepare(`INSERT INTO tester_invitations(id,email_hint,target_user_id,token_hash,status,created_by,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,clean(emailHint,120),targetUserId,createHash("sha256").update(token).digest("hex"),"PENDING",actorUserId,expiresAt,now,now);return {id,status:"PENDING",targetUserId,emailHint:clean(emailHint,120),expiresAt,token};}

export function createTestCampaign(input={},actorUserId){const title=clean(input.title,180);if(!title)throw new Error("Informe o título da campanha.");const gameId=input.gameId&&db.prepare(`SELECT id FROM games WHERE id=?`).get(input.gameId)?input.gameId:null,runId=input.constructionRunId&&db.prepare(`SELECT id FROM construction_runs WHERE id=?`).get(input.constructionRunId)?input.constructionRunId:null,checklist=(input.checklist||[]).slice(0,30).map((item,index)=>({id:clean(item.id||`check-${index+1}`,60),label:clean(item.label||item,220),required:item.required!==false})).filter(x=>x.label),id=randomUUID(),now=nowIso();db.prepare(`INSERT INTO test_campaigns(id,game_id,construction_run_id,title,description,checklist_json,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,gameId,runId,title,clean(input.description,1500),json(checklist),input.status==="ACTIVE"?"ACTIVE":"DRAFT",actorUserId,now,now);return mapCampaign(db.prepare(`SELECT * FROM test_campaigns WHERE id=?`).get(id));}

export function assignTester(campaignId,testerUserId,actorUserId){const campaign=mapCampaign(db.prepare(`SELECT * FROM test_campaigns WHERE id=?`).get(campaignId));if(!campaign)throw new Error("Campanha não encontrada.");const access=accessSnapshotForUser(testerUserId);if(access.staffRole!=="TESTER")throw new Error("O usuário precisa ter o papel TESTER.");const now=nowIso();db.prepare(`INSERT INTO test_campaign_assignments(campaign_id,tester_user_id,status,checklist_results_json,assigned_by,assigned_at,updated_at) VALUES(?,?,'ASSIGNED','{}',?,?,?) ON CONFLICT(campaign_id,tester_user_id) DO UPDATE SET status='ASSIGNED',assigned_by=excluded.assigned_by,updated_at=excluded.updated_at`).run(campaignId,testerUserId,actorUserId,now,now);return {campaignId,testerUserId,status:"ASSIGNED",assignedAt:now};}

export function testerAssignments(testerUserId){return db.prepare(`SELECT c.*,a.status assignment_status,a.checklist_results_json,a.assigned_at,a.updated_at assignment_updated_at FROM test_campaign_assignments a JOIN test_campaigns c ON c.id=a.campaign_id WHERE a.tester_user_id=? AND a.status<>'REMOVED' ORDER BY a.updated_at DESC`).all(testerUserId).map(row=>({...mapCampaign(row),assignment:{status:row.assignment_status,checklistResults:parseJson(row.checklist_results_json,{}),assignedAt:row.assigned_at,updatedAt:row.assignment_updated_at},preview:{constructionRunId:row.construction_run_id,authorized:Boolean(row.construction_run_id)}}));}

export function saveChecklist(campaignId,testerUserId,results={}){const row=db.prepare(`SELECT status FROM test_campaign_assignments WHERE campaign_id=? AND tester_user_id=?`).get(campaignId,testerUserId);if(!row)throw new Error("Esta campanha não está atribuída a você.");const campaign=mapCampaign(db.prepare(`SELECT * FROM test_campaigns WHERE id=?`).get(campaignId)),allowed=new Set(campaign.checklist.map(x=>x.id)),cleanResults={};for(const [key,value] of Object.entries(results||{}))if(allowed.has(key)&&["PASS","FAIL","SKIP"].includes(String(value).toUpperCase()))cleanResults[key]=String(value).toUpperCase();db.prepare(`UPDATE test_campaign_assignments SET status='IN_PROGRESS',checklist_results_json=?,updated_at=? WHERE campaign_id=? AND tester_user_id=?`).run(json(cleanResults),nowIso(),campaignId,testerUserId);return {campaignId,results:cleanResults,status:"IN_PROGRESS"};}

export function createTestFeedback(input={},testerUserId){const campaignId=String(input.campaignId||""),assignment=db.prepare(`SELECT 1 FROM test_campaign_assignments WHERE campaign_id=? AND tester_user_id=? AND status<>'REMOVED'`).get(campaignId,testerUserId);if(!assignment)throw new Error("Esta campanha não está atribuída a você.");const category=String(input.category||"OTHER").toUpperCase();if(!FEEDBACK_CATEGORIES.has(category))throw new Error("Categoria de feedback inválida.");const title=clean(input.title,180),description=clean(input.description,3000);if(!title||!description)throw new Error("Título e descrição são obrigatórios.");const pageId=input.pageId&&db.prepare(`SELECT id FROM pages WHERE id=?`).get(input.pageId)?input.pageId:null,pageVersionId=input.pageVersionId&&db.prepare(`SELECT id FROM page_versions WHERE id=?`).get(input.pageVersionId)?input.pageVersionId:null,runId=input.constructionRunId&&db.prepare(`SELECT id FROM construction_runs WHERE id=?`).get(input.constructionRunId)?input.constructionRunId:null,id=randomUUID(),now=nowIso();transaction(()=>{db.prepare(`INSERT INTO test_feedback(id,campaign_id,tester_user_id,page_id,page_version_id,construction_run_id,category,title,description,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'OPEN',?,?)`).run(id,campaignId,testerUserId,pageId,pageVersionId,runId,category,title,description,now,now);db.prepare(`UPDATE test_campaign_assignments SET status='SUBMITTED',updated_at=? WHERE campaign_id=? AND tester_user_id=?`).run(now,campaignId,testerUserId);});return mapFeedback(db.prepare(`SELECT * FROM test_feedback WHERE id=?`).get(id));}

export function listTestFeedback({testerUserId=null,campaignId=null,status=null,limit=100}={}){const where=[],args=[];if(testerUserId){where.push(`tester_user_id=?`);args.push(testerUserId);}if(campaignId){where.push(`campaign_id=?`);args.push(campaignId);}if(status){where.push(`status=?`);args.push(status);}return db.prepare(`SELECT * FROM test_feedback${where.length?` WHERE ${where.join(" AND ")}`:""} ORDER BY updated_at DESC LIMIT ?`).all(...args,Math.min(300,Math.max(1,Number(limit)||100))).map(mapFeedback);}

export function updateTestFeedback(id,{status,developerResponse=""}={}){const allowed=new Set(["OPEN","ACKNOWLEDGED","CHANGES_REQUESTED","RESOLVED","CLOSED"]),next=String(status||"").toUpperCase();if(!allowed.has(next))throw new Error("Status de feedback inválido.");db.prepare(`UPDATE test_feedback SET status=?,developer_response=?,updated_at=? WHERE id=?`).run(next,clean(developerResponse,2000),nowIso(),id);const feedback=mapFeedback(db.prepare(`SELECT * FROM test_feedback WHERE id=?`).get(id));if(!feedback)throw new Error("Feedback não encontrado.");return feedback;}

export function listCampaigns({limit=100}={}){return db.prepare(`SELECT * FROM test_campaigns ORDER BY updated_at DESC LIMIT ?`).all(Math.min(200,Math.max(1,Number(limit)||100))).map(mapCampaign);}

