import { randomUUID } from "node:crypto";
import { db, json, nowIso, parseJson } from "../database/connection.mjs";
import { stableId } from "../knowledge/normalize.mjs";
import { publishCoreEvent } from "./message-bus.mjs";
import { recordOperation } from "./metrics.mjs";

const TERMINAL=new Set(["COMPLETED","FAILED","CANCELLED","BLOCKED"]);
function map(r){return r?{id:r.id,key:r.job_key,gameId:r.game_id,entityId:r.entity_id,manifestId:r.manifest_id,manifestItemId:r.manifest_item_id,jobType:r.job_type,state:r.state,priority:Number(r.priority),revision:Number(r.revision),attempts:Number(r.attempts),maxAttempts:Number(r.max_attempts),availableAt:r.available_at,leaseOwner:r.lease_owner,leaseExpiresAt:r.lease_expires_at,errorCode:r.last_error_code,errorMessage:r.last_error_message,input:parseJson(r.input_json,{}),output:parseJson(r.output_json,{}),createdAt:r.created_at,updatedAt:r.updated_at,completedAt:r.completed_at}:null;}
export function deterministicJobKey({gameId,entityId=null,jobType,revision=1,manifestItemId=null}={}){return `${gameId}:${entityId||manifestItemId||"GAME"}:${String(jobType).toUpperCase()}:${Number(revision)||1}`;}
export function enqueueJob(input={}){const started=Date.now(),jobType=String(input.jobType||"").toUpperCase();if(!input.gameId||!jobType)throw new Error("gameId and jobType required");const key=input.key||deterministicJobKey(input),id=stableId("gi98-job",key),now=nowIso(),available=input.availableAt||now;db.prepare(`INSERT INTO gi_jobs(id,job_key,game_id,entity_id,manifest_id,manifest_item_id,job_type,state,priority,revision,attempts,max_attempts,available_at,input_json,output_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'QUEUED',?,?,0,?,?,?,'{}',?,?) ON CONFLICT(job_key) DO UPDATE SET state=CASE WHEN gi_jobs.state IN ('COMPLETED','RUNNING') THEN gi_jobs.state ELSE 'QUEUED' END,priority=MIN(gi_jobs.priority,excluded.priority),available_at=CASE WHEN gi_jobs.state IN ('COMPLETED','RUNNING') THEN gi_jobs.available_at ELSE excluded.available_at END,input_json=excluded.input_json,updated_at=excluded.updated_at`).run(id,key,input.gameId,input.entityId||null,input.manifestId||null,input.manifestItemId||null,jobType,Number(input.priority??50),Number(input.revision||1),Math.max(1,Number(input.maxAttempts||4)),available,json(input.input||{}),now,now);const job=getJobById(id);recordOperation({type:"CORE",name:"JOB_ENQUEUE",gameId:job.gameId,entityId:job.entityId,durationMs:Date.now()-started,aiAvoided:true,details:{jobType,key}});publishCoreEvent("JOB_QUEUED",{gameId:job.gameId,entityId:job.entityId,subjectType:"JOB",subjectId:job.id,jobType});return job;}
export function getJobById(id){return map(db.prepare(`SELECT * FROM gi_jobs WHERE id=?`).get(id));}
export function listJobs({gameId=null,state=null,jobType=null,limit=100,offset=0}={}){const where=["1=1"],args=[];if(gameId){where.push("game_id=?");args.push(gameId);}if(state){where.push("state=?");args.push(String(state).toUpperCase());}if(jobType){where.push("job_type=?");args.push(String(jobType).toUpperCase());}const n=Math.min(500,Math.max(1,Number(limit)||100)),o=Math.max(0,Number(offset)||0),clause=where.join(" AND ");return {entries:db.prepare(`SELECT * FROM gi_jobs WHERE ${clause} ORDER BY priority,available_at,created_at LIMIT ? OFFSET ?`).all(...args,n,o).map(map),total:Number(db.prepare(`SELECT COUNT(*) count FROM gi_jobs WHERE ${clause}`).get(...args)?.count||0),limit:n,offset:o};}
export function leaseNextJob({workerId,jobTypes=[],leaseMs=60000}={}){const now=nowIso(),types=jobTypes.map(x=>String(x).toUpperCase()),where=types.length?`AND job_type IN (${types.map(()=>"?").join(",")})`:"";const row=db.prepare(`SELECT * FROM gi_jobs WHERE state IN ('QUEUED','RETRY_SCHEDULED') AND available_at<=? AND (lease_expires_at='' OR lease_expires_at<?) ${where} ORDER BY priority,available_at,created_at LIMIT 1`).get(now,now,...types);if(!row)return null;const expires=new Date(Date.now()+Math.max(10000,Number(leaseMs)||60000)).toISOString();const result=db.prepare(`UPDATE gi_jobs SET state='RUNNING',lease_owner=?,lease_expires_at=?,attempts=attempts+1,updated_at=? WHERE id=? AND state IN ('QUEUED','RETRY_SCHEDULED')`).run(workerId,expires,now,row.id);return Number(result.changes||0)?getJobById(row.id):null;}
export function completeJob(id,output={}){const job=getJobById(id);if(!job)return null;const now=nowIso();db.prepare(`UPDATE gi_jobs SET state='COMPLETED',output_json=?,lease_owner='',lease_expires_at='',last_error_code='',last_error_message='',updated_at=?,completed_at=? WHERE id=?`).run(json(output||{}),now,now,id);publishCoreEvent("JOB_COMPLETED",{gameId:job.gameId,entityId:job.entityId,subjectType:"JOB",subjectId:id,jobType:job.jobType});return getJobById(id);}
export function failJob(id,{code="JOB_FAILED",message="",retryable=true,details={}}={}){const job=getJobById(id);if(!job)return null;const exhausted=job.attempts>=job.maxAttempts,nextState=retryable&&!exhausted?"RETRY_SCHEDULED":"FAILED",delay=Math.min(6*60*60*1000,Math.max(15000,15000*(2**Math.max(0,job.attempts-1)))),available=nextState==="RETRY_SCHEDULED"?new Date(Date.now()+delay).toISOString():job.availableAt,now=nowIso();db.prepare(`UPDATE gi_jobs SET state=?,available_at=?,lease_owner='',lease_expires_at='',last_error_code=?,last_error_message=?,output_json=?,updated_at=?,completed_at=? WHERE id=?`).run(nextState,available,String(code).slice(0,120),String(message).slice(0,900),json(details||{}),now,nextState==="FAILED"?now:"",id);publishCoreEvent(nextState==="FAILED"?"JOB_FAILED":"JOB_RETRY_SCHEDULED",{gameId:job.gameId,entityId:job.entityId,subjectType:"JOB",subjectId:id,jobType:job.jobType,errorCode:code});return getJobById(id);}
export function recoverExpiredJobs(){const now=nowIso();const r=db.prepare(`UPDATE gi_jobs SET state='RETRY_SCHEDULED',lease_owner='',lease_expires_at='',available_at=?,last_error_code='LEASE_EXPIRED',updated_at=? WHERE state='RUNNING' AND lease_expires_at<>'' AND lease_expires_at<?`).run(now,now,now);return Number(r.changes||0);}
export function queueSummary(gameId=null){const rows=gameId?db.prepare(`SELECT job_type,state,COUNT(*) count FROM gi_jobs WHERE game_id=? GROUP BY job_type,state`).all(gameId):db.prepare(`SELECT job_type,state,COUNT(*) count FROM gi_jobs GROUP BY job_type,state`).all();const out={};for(const r of rows){out[r.job_type]??={};out[r.job_type][r.state]=Number(r.count);}return out;}
export function hasPendingJobs(gameId){return Boolean(db.prepare(`SELECT 1 FROM gi_jobs WHERE game_id=? AND state IN ('QUEUED','RUNNING','RETRY_SCHEDULED') LIMIT 1`).get(gameId));}
export function terminalJob(job){return Boolean(job&&TERMINAL.has(job.state));}
