import { randomUUID } from "node:crypto";
import { db, json, nowIso, parseJson } from "../database/connection.mjs";
import { stableId } from "../knowledge/normalize.mjs";
import { publishCoreEvent } from "./message-bus.mjs";
import { recordOperation } from "./metrics.mjs";

export const UNIVERSE_STATES=["DISCOVERED","CANONICALIZED","CLASSIFIED","PLANNED","KNOWLEDGE_REQUIRED","RESEARCH_QUEUED","RESEARCHING","KNOWLEDGE_VERIFIED","READY_TO_BUILD","BUILDING","CONTENT_READY","IMAGE_RESOLVING","RELATIONSHIPS_BUILDING","INDEXING","PUBLISHED","WAITING_KNOWLEDGE","NEEDS_REVIEW","IMAGE_DEGRADED","RESEARCH_FAILED","BUILD_FAILED","BLOCKED","RETRY_SCHEDULED"];
const graph={
 DISCOVERED:["CANONICALIZED","BLOCKED"],CANONICALIZED:["CLASSIFIED","NEEDS_REVIEW","BLOCKED"],CLASSIFIED:["PLANNED","NEEDS_REVIEW"],PLANNED:["KNOWLEDGE_REQUIRED","CONTENT_READY"],KNOWLEDGE_REQUIRED:["RESEARCH_QUEUED","WAITING_KNOWLEDGE"],RESEARCH_QUEUED:["RESEARCHING","RETRY_SCHEDULED"],RESEARCHING:["KNOWLEDGE_VERIFIED","WAITING_KNOWLEDGE","RESEARCH_FAILED","RETRY_SCHEDULED"],KNOWLEDGE_VERIFIED:["READY_TO_BUILD"],READY_TO_BUILD:["BUILDING"],BUILDING:["CONTENT_READY","BUILD_FAILED","RETRY_SCHEDULED"],CONTENT_READY:["IMAGE_RESOLVING","RELATIONSHIPS_BUILDING","INDEXING","PUBLISHED"],IMAGE_RESOLVING:["RELATIONSHIPS_BUILDING","IMAGE_DEGRADED","RETRY_SCHEDULED"],RELATIONSHIPS_BUILDING:["INDEXING","RETRY_SCHEDULED"],INDEXING:["PUBLISHED","RETRY_SCHEDULED"],IMAGE_DEGRADED:["RELATIONSHIPS_BUILDING","INDEXING","PUBLISHED","RETRY_SCHEDULED"],WAITING_KNOWLEDGE:["RESEARCH_QUEUED","NEEDS_REVIEW"],RESEARCH_FAILED:["RETRY_SCHEDULED","NEEDS_REVIEW"],BUILD_FAILED:["RETRY_SCHEDULED","NEEDS_REVIEW"],RETRY_SCHEDULED:["RESEARCH_QUEUED","READY_TO_BUILD","IMAGE_RESOLVING","RELATIONSHIPS_BUILDING","INDEXING","BLOCKED"],NEEDS_REVIEW:["CANONICALIZED","PLANNED","RESEARCH_QUEUED","READY_TO_BUILD","PUBLISHED"],BLOCKED:["RETRY_SCHEDULED"]};
function map(r){return r?{id:r.id,gameId:r.game_id,entityId:r.entity_id,manifestItemId:r.manifest_item_id,currentState:r.current_state,knowledgeStatus:r.knowledge_status,imageStatus:r.image_status,pageStatus:r.page_status,relationshipStatus:r.relationship_status,indexStatus:r.index_status,publishStatus:r.publish_status,blockingReasons:parseJson(r.blocking_reasons_json,[]),retryCount:Number(r.retry_count||0),revision:Number(r.revision||1),createdAt:r.created_at,updatedAt:r.updated_at}:null;}
export function ensureUniverseState({gameId,entityId=null,manifestItemId=null,initialState="DISCOVERED"}={}){if(!gameId)throw new Error("gameId required");const id=stableId("u98-state",gameId,entityId||"GAME");const now=nowIso();db.prepare(`INSERT INTO gi_universe_states(id,game_id,entity_id,manifest_item_id,current_state,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(game_id,entity_id) DO UPDATE SET manifest_item_id=COALESCE(excluded.manifest_item_id,gi_universe_states.manifest_item_id),updated_at=excluded.updated_at`).run(id,gameId,entityId,manifestItemId,initialState,now,now);return getUniverseState(id);}
export function getUniverseState(idOrEntityId,gameId=null){const row=gameId?db.prepare(`SELECT * FROM gi_universe_states WHERE game_id=? AND entity_id IS ?`).get(gameId,idOrEntityId):db.prepare(`SELECT * FROM gi_universe_states WHERE id=? OR entity_id=? LIMIT 1`).get(idOrEntityId,idOrEntityId);return map(row);}
export function transitionUniverseState(stateId,toState,{reason="",source="CORE",details={},force=false,patch={}}={}){const started=Date.now(),current=getUniverseState(stateId);if(!current)throw new Error("Universe state not found");const to=String(toState).toUpperCase();if(!UNIVERSE_STATES.includes(to))throw new Error(`Invalid Universe state ${to}`);if(!force&&current.currentState!==to&&!(graph[current.currentState]||[]).includes(to))throw new Error(`Invalid transition ${current.currentState} -> ${to}`);const mapCols={knowledgeStatus:"knowledge_status",imageStatus:"image_status",pageStatus:"page_status",relationshipStatus:"relationship_status",indexStatus:"index_status",publishStatus:"publish_status",blockingReasons:"blocking_reasons_json",retryCount:"retry_count"},sets=[`current_state=?`,`updated_at=?`],args=[to,nowIso()];for(const [k,v] of Object.entries(patch||{})){if(!mapCols[k])continue;sets.push(`${mapCols[k]}=?`);args.push(k==="blockingReasons"?json(v||[]):v);}if(current.currentState!==to)sets.push(`revision=revision+1`);args.push(current.id);db.prepare(`UPDATE gi_universe_states SET ${sets.join(",")} WHERE id=?`).run(...args);db.prepare(`INSERT INTO gi_state_transitions(id,universe_state_id,from_state,to_state,reason,source,details_json,created_at) VALUES(?,?,?,?,?,?,?,?)`).run(`tr98-${randomUUID()}`,current.id,current.currentState,to,String(reason||"").slice(0,240),String(source||"CORE").slice(0,80),json(details||{}),nowIso());const next=getUniverseState(current.id);publishCoreEvent("UNIVERSE_STATE_CHANGED",{gameId:next.gameId,entityId:next.entityId,subjectType:"UNIVERSE_STATE",subjectId:next.id,fromState:current.currentState,toState:to});recordOperation({type:"CORE",name:"STATE_TRANSITION",gameId:next.gameId,entityId:next.entityId,durationMs:Date.now()-started,aiAvoided:true,details:{from:current.currentState,to}});return next;}
export function listUniverseStates(gameId,{limit=500}={}){return db.prepare(`SELECT * FROM gi_universe_states WHERE game_id=? ORDER BY updated_at DESC LIMIT ?`).all(gameId,Math.min(1000,Math.max(1,Number(limit)||500))).map(map);}
