import { randomUUID } from "node:crypto";
import { db, json, nowIso } from "../database/connection.mjs";
import { completeJob, failJob, leaseNextJob, recoverExpiredJobs } from "./job-engine.mjs";
import { routeJobCompletion } from "./orchestrator.mjs";
import { onCoreEvent, publishCoreEvent } from "./message-bus.mjs";
import { processUniverseJob } from "../universe/universe-builder-v2.mjs";
import { recordOperation } from "./metrics.mjs";

const groups=[
  {type:"CONTROL",jobTypes:["DISCOVERY","CANONICALIZE","CLASSIFY"],concurrency:Number(process.env.GAMEINDEX_CORE98_CONTROL_CONCURRENCY||4)},
  {type:"RESEARCH",jobTypes:["RESEARCH"],concurrency:Number(process.env.GAMEINDEX_CORE98_RESEARCH_CONCURRENCY||2)},
  {type:"CONTENT",jobTypes:["CONTENT_BUILD"],concurrency:Number(process.env.GAMEINDEX_CORE98_CONTENT_CONCURRENCY||3)},
  {type:"IMAGE",jobTypes:["IMAGE"],concurrency:Number(process.env.GAMEINDEX_CORE98_IMAGE_CONCURRENCY||4)},
  {type:"RELATION_INDEX",jobTypes:["RELATIONSHIP","INDEX"],concurrency:Number(process.env.GAMEINDEX_CORE98_LIGHT_CONCURRENCY||5)}
].map(g=>({...g,concurrency:Math.max(1,Math.min(8,Number(g.concurrency)||1))}));
const active=new Map(groups.map(g=>[g.type,0]));let timer=null,scheduled=false,started=false;
function heartbeat(workerId,workerType,{status="IDLE",activeJobId="",processedDelta=0,failedDelta=0,metadata={}}={}){const now=nowIso();db.prepare(`INSERT INTO gi_worker_heartbeats(worker_id,worker_type,status,active_job_id,processed_count,failed_count,last_heartbeat_at,started_at,metadata_json) VALUES(?,?,?,?,?,?,?, ?,?) ON CONFLICT(worker_id) DO UPDATE SET status=excluded.status,active_job_id=excluded.active_job_id,processed_count=gi_worker_heartbeats.processed_count+?,failed_count=gi_worker_heartbeats.failed_count+?,last_heartbeat_at=excluded.last_heartbeat_at,metadata_json=excluded.metadata_json`).run(workerId,workerType,status,activeJobId,Math.max(0,processedDelta),Math.max(0,failedDelta),now,now,json(metadata),Math.max(0,processedDelta),Math.max(0,failedDelta));}
async function runOne(group,slot){const workerId=`gi98-${group.type.toLowerCase()}-${slot}`;const job=leaseNextJob({workerId,jobTypes:group.jobTypes,leaseMs:group.type==="RESEARCH"?180000:90000});if(!job){heartbeat(workerId,group.type,{status:"IDLE"});return false;}active.set(group.type,(active.get(group.type)||0)+1);heartbeat(workerId,group.type,{status:"RUNNING",activeJobId:job.id});const startedAt=Date.now();try{const result=await processUniverseJob(job);completeJob(job.id,result);routeJobCompletion(job,result);heartbeat(workerId,group.type,{status:"IDLE",processedDelta:1});recordOperation({type:"WORKER",name:`${group.type}_JOB`,gameId:job.gameId,entityId:job.entityId,durationMs:Date.now()-startedAt,success:true,aiAvoided:true,details:{jobType:job.jobType}});return true;}catch(error){const retryable=error?.retryable!==false;failJob(job.id,{code:error?.code||"WORKER_JOB_FAILED",message:String(error?.message||error),retryable,details:{jobType:job.jobType}});heartbeat(workerId,group.type,{status:"IDLE",failedDelta:1});recordOperation({type:"WORKER",name:`${group.type}_JOB`,gameId:job.gameId,entityId:job.entityId,durationMs:Date.now()-startedAt,success:false,aiAvoided:true,details:{jobType:job.jobType,error:String(error?.message||error)}});return true;}finally{active.set(group.type,Math.max(0,(active.get(group.type)||1)-1));}}
async function drain(){scheduled=false;if(!started)return;let didWork=false;for(const group of groups){const free=Math.max(0,group.concurrency-(active.get(group.type)||0));if(!free)continue;const results=await Promise.all(Array.from({length:free},(_,i)=>runOne(group,i)));if(results.some(Boolean))didWork=true;}if(didWork)scheduleDrain(30);}
function scheduleDrain(delay=0){if(!started||scheduled)return;scheduled=true;setTimeout(()=>drain().catch(error=>{scheduled=false;console.error("[GI Core 0.98 worker]",error?.message||error);}),Math.max(0,delay));}
function detectStalls(){if(!started)return;const cutoff=new Date(Date.now()-10*60*1000).toISOString(),rows=db.prepare(`SELECT id,game_id,entity_id,job_type,state,updated_at FROM gi_jobs WHERE state IN ('QUEUED','RUNNING','RETRY_SCHEDULED') AND updated_at<? LIMIT 100`).all(cutoff);for(const row of rows){const type=row.state==="RUNNING"?"WORKER_OFFLINE":`${row.job_type}_STALL`,fingerprint=`${row.game_id}:${row.entity_id||"GAME"}:${type}`.slice(0,500),now=nowIso();db.prepare(`INSERT INTO gi_stall_events(id,game_id,entity_id,stall_type,status,fingerprint,details_json,first_seen_at,last_seen_at) VALUES(?,?,?,?, 'OPEN',?,?,?,?) ON CONFLICT(fingerprint) DO UPDATE SET status='OPEN',details_json=excluded.details_json,last_seen_at=excluded.last_seen_at`).run(`stall98-${randomUUID()}`,row.game_id,row.entity_id,type,fingerprint,json({jobId:row.id,jobType:row.job_type,state:row.state,updatedAt:row.updated_at}),now,now);}if(rows.length)publishCoreEvent("PIPELINE_STALL_DETECTED",{subjectType:"STALL",subjectId:"",count:rows.length});}
export function startCore98Workers(){if(started)return core98WorkerStatus();if(String(process.env.GAMEINDEX_CORE98_ENABLED??"true").toLowerCase()==="false")return {enabled:false};started=true;const recovered=recoverExpiredJobs();for(const group of groups)for(let i=0;i<group.concurrency;i++)heartbeat(`gi98-${group.type.toLowerCase()}-${i}`,group.type,{status:"IDLE",metadata:{jobTypes:group.jobTypes}});onCoreEvent("JOB_QUEUED",()=>scheduleDrain(5));onCoreEvent("JOB_RETRY_SCHEDULED",()=>scheduleDrain(50));timer=setInterval(()=>{scheduleDrain(0);detectStalls();},4000);timer.unref?.();scheduleDrain(0);return {enabled:true,recovered,...core98WorkerStatus()};}
export function core98WorkerStatus(){const workers=db.prepare(`SELECT worker_id,worker_type,status,active_job_id,processed_count,failed_count,last_heartbeat_at FROM gi_worker_heartbeats ORDER BY worker_type,worker_id`).all();return {enabled:started,groups:groups.map(g=>({type:g.type,jobTypes:g.jobTypes,concurrency:g.concurrency,active:active.get(g.type)||0})),workers,stallsOpen:Number(db.prepare(`SELECT COUNT(*) count FROM gi_stall_events WHERE status='OPEN'`).get()?.count||0)};}
