export const GAME_SEEDS = [
  { name:"Minecraft", aliases:["Mine","Minecraft Java","Minecraft Bedrock","MC"], description:"Sandbox de exploração, construção e sobrevivência em mundos formados por blocos, com diferentes modos de jogo e sistemas de criação.", developer:"Mojang Studios", publisher:"Mojang Studios", releaseDate:"2011", platforms:["PC","Consoles","Mobile"], genres:["Sandbox","Sobrevivência"], franchise:"Minecraft", officialUrl:"https://www.minecraft.net/", template:"sandbox", tabs:["overview","gameplay","items","mobs","maps","lore","guides"], visualQuery:"Minecraft video game" },
  { name:"Fortnite", aliases:["Fort","Fortnite Battle Royale"], description:"Plataforma de experiências da Epic Games conhecida pelo Battle Royale, temporadas, eventos e conteúdo que muda ao longo do tempo.", developer:"Epic Games", publisher:"Epic Games", releaseDate:"2017", platforms:["PC","Consoles","Mobile"], genres:["Battle Royale","Ação"], franchise:"Fortnite", officialUrl:"https://www.fortnite.com/", template:"battle-royale", tabs:["overview","gameplay","weapons","maps","skins","seasons","lore","guides"], visualQuery:"Fortnite video game" },
  { name:"Roblox", aliases:["Roblox Platform"], description:"Plataforma de criação e distribuição de experiências feitas por usuários, com avatares, economia virtual e ferramentas de desenvolvimento.", developer:"Roblox Corporation", publisher:"Roblox Corporation", releaseDate:"2006", platforms:["PC","Consoles","Mobile"], genres:["Plataforma","UGC"], franchise:"Roblox", officialUrl:"https://www.roblox.com/", template:"generic", tabs:["overview","experiences","gameplay","items","codes","guides"], visualQuery:"Roblox platform" },
  { name:"Counter-Strike 2", aliases:["CS2","Counter Strike 2"], description:"FPS competitivo em equipes com foco em precisão, economia, utilitários e objetivos de ataque e defesa.", developer:"Valve", publisher:"Valve", releaseDate:"2023", platforms:["PC"], genres:["FPS","Competitivo"], franchise:"Counter-Strike", officialUrl:"https://www.counter-strike.net/cs2", template:"fps", tabs:["overview","gameplay","weapons","maps","skins","ranks","guides"], visualQuery:"Counter-Strike 2" },
  { name:"Sonic the Hedgehog", aliases:["Sonic","Sonic 1"], description:"Jogo de plataforma clássico da SEGA centrado em velocidade, anéis e fases divididas em zonas.", developer:"SEGA", publisher:"SEGA", releaseDate:"1991", platforms:["Múltiplas plataformas"], genres:["Plataforma"], franchise:"Sonic the Hedgehog", officialUrl:"https://www.sonicthehedgehog.com/", template:"platformer", visualQuery:"Sonic the Hedgehog 1991 video game" },
  { name:"Sonic the Hedgehog 2", aliases:["Sonic 2"], description:"Sequência clássica que expandiu a velocidade e as zonas da série e introduziu Tails como parceiro de Sonic.", developer:"SEGA", publisher:"SEGA", releaseDate:"1992", platforms:["Múltiplas plataformas"], genres:["Plataforma"], franchise:"Sonic the Hedgehog", officialUrl:"https://www.sonicthehedgehog.com/", template:"platformer", visualQuery:"Sonic the Hedgehog 2 1992 video game" },
  { name:"Sonic the Hedgehog 3", aliases:["Sonic 3"], description:"Terceiro jogo principal da fase clássica, com novas zonas, escudos elementais e a estreia de Knuckles na história da série.", developer:"SEGA", publisher:"SEGA", releaseDate:"1994", platforms:["Múltiplas plataformas"], genres:["Plataforma"], franchise:"Sonic the Hedgehog", officialUrl:"https://www.sonicthehedgehog.com/", template:"platformer", visualQuery:"Sonic the Hedgehog 3 1994 video game" },
  { name:"Sonic 3 & Knuckles", aliases:["Sonic 3 and Knuckles","Sonic & Knuckles"], description:"Experiência combinada das campanhas de Sonic 3 e Sonic & Knuckles, formando uma aventura clássica maior e contínua.", developer:"SEGA", publisher:"SEGA", releaseDate:"1994", platforms:["Múltiplas plataformas"], genres:["Plataforma"], franchise:"Sonic the Hedgehog", officialUrl:"https://www.sonicthehedgehog.com/", template:"platformer", visualQuery:"Sonic 3 & Knuckles" },
  { name:"Marvel's Spider-Man", aliases:["Spider-Man","Spiderman 1","Marvel Spider Man"], description:"Ação em mundo aberto centrada em Peter Parker, exploração de Nova York, combate acrobático e deslocamento por teias.", developer:"Insomniac Games", publisher:"Sony Interactive Entertainment", releaseDate:"2018", platforms:["PlayStation","PC"], genres:["Ação","Mundo aberto"], franchise:"Marvel's Spider-Man", officialUrl:"", template:"open-world", tabs:["overview","story","characters","gameplay","abilities","maps","missions","guides"], visualQuery:"Marvel's Spider-Man 2018 video game" },
  { name:"Marvel's Spider-Man: Miles Morales", aliases:["Miles Morales","Spider-Man Miles Morales"], description:"Aventura protagonizada por Miles Morales com habilidades próprias, exploração urbana e uma história independente dentro da série.", developer:"Insomniac Games", publisher:"Sony Interactive Entertainment", releaseDate:"2020", platforms:["PlayStation","PC"], genres:["Ação","Mundo aberto"], franchise:"Marvel's Spider-Man", officialUrl:"", template:"open-world", tabs:["overview","story","characters","gameplay","abilities","maps","missions","guides"], visualQuery:"Marvel's Spider-Man Miles Morales video game" },
  { name:"Marvel's Spider-Man 2", aliases:["Spider-Man 2","Spiderman 2"], description:"Sequência com Peter Parker e Miles Morales, ampliando a exploração, os poderes e a narrativa da série da Insomniac.", developer:"Insomniac Games", publisher:"Sony Interactive Entertainment", releaseDate:"2023", platforms:["PlayStation","PC"], genres:["Ação","Mundo aberto"], franchise:"Marvel's Spider-Man", officialUrl:"", template:"open-world", tabs:["overview","story","characters","gameplay","abilities","maps","missions","guides"], visualQuery:"Marvel's Spider-Man 2 video game" },
  { name:"Grand Theft Auto III", aliases:["GTA III","GTA 3"], description:"Ação em mundo aberto ambientada em Liberty City e marco da transição 3D da série Grand Theft Auto.", developer:"Rockstar North", publisher:"Rockstar Games", releaseDate:"2001", platforms:["Múltiplas plataformas"], genres:["Ação","Mundo aberto"], franchise:"Grand Theft Auto", officialUrl:"https://www.rockstargames.com/", template:"open-world", visualQuery:"Grand Theft Auto III" },
  { name:"Grand Theft Auto: Vice City", aliases:["GTA Vice City","Vice City"], description:"Ação em mundo aberto ambientada em Vice City, com forte identidade inspirada nos anos 1980.", developer:"Rockstar North", publisher:"Rockstar Games", releaseDate:"2002", platforms:["Múltiplas plataformas"], genres:["Ação","Mundo aberto"], franchise:"Grand Theft Auto", officialUrl:"https://www.rockstargames.com/", template:"open-world", visualQuery:"Grand Theft Auto Vice City" },
  { name:"Grand Theft Auto: San Andreas", aliases:["GTA San Andreas","GTA SA","San Andreas"], description:"Ação em mundo aberto que acompanha Carl Johnson em uma grande região com três cidades principais e áreas rurais.", developer:"Rockstar North", publisher:"Rockstar Games", releaseDate:"2004", platforms:["Múltiplas plataformas"], genres:["Ação","Mundo aberto"], franchise:"Grand Theft Auto", officialUrl:"https://www.rockstargames.com/", template:"open-world", visualQuery:"Grand Theft Auto San Andreas" },
  { name:"Grand Theft Auto IV", aliases:["GTA IV","GTA 4"], description:"Ação em mundo aberto centrada em Niko Bellic e uma nova interpretação de Liberty City.", developer:"Rockstar North", publisher:"Rockstar Games", releaseDate:"2008", platforms:["PC","Consoles"], genres:["Ação","Mundo aberto"], franchise:"Grand Theft Auto", officialUrl:"https://www.rockstargames.com/", template:"open-world", visualQuery:"Grand Theft Auto IV" },
  { name:"Grand Theft Auto V", aliases:["GTA V","GTA 5","GTA Online"], description:"Ação em mundo aberto com três protagonistas e uma ampla versão de Los Santos e Blaine County.", developer:"Rockstar North", publisher:"Rockstar Games", releaseDate:"2013", platforms:["PC","Consoles"], genres:["Ação","Mundo aberto"], franchise:"Grand Theft Auto", officialUrl:"https://www.rockstargames.com/gta-v", template:"open-world", visualQuery:"Grand Theft Auto V" },
  { name:"Grand Theft Auto VI", aliases:["GTA VI","GTA 6"], description:"Novo título principal da série Grand Theft Auto. Informações voláteis, como lançamento e plataformas, devem ser revalidadas por fontes atuais antes de serem tratadas como definitivas.", developer:"Rockstar Games", publisher:"Rockstar Games", releaseDate:"", platforms:[], genres:["Ação","Mundo aberto"], franchise:"Grand Theft Auto", officialUrl:"https://www.rockstargames.com/VI", template:"open-world", visualQuery:"Grand Theft Auto VI" }
];

export const ENTITY_SEEDS = [
  // Minecraft
  { game:"Minecraft", name:"Enderman", type:"mob", aliases:["Endermen"], summary:"Mob alto e neutro que pode se tornar hostil quando provocado ou encarado diretamente.", tab:"mobs", section:"neutral", claims:["Endermen podem se teletransportar e são normalmente neutros até serem provocados.","Endermen podem derrubar Ender Pearls quando derrotados."], relationships:[{type:"drops",target:"Ender Pearl"},{type:"appears_in",target:"The End"}] },
  { game:"Minecraft", name:"Ender Pearl", type:"item", aliases:["Pérola do End"], summary:"Item associado aos Endermen e usado em progressão e teletransporte.", tab:"items", section:"materials", claims:["Ender Pearls podem ser arremessadas para teletransportar o jogador.","Elas participam da criação do Eye of Ender."], relationships:[{type:"used_for",target:"Eye of Ender"}] },
  { game:"Minecraft", name:"Eye of Ender", type:"item", aliases:["Olho do End"], summary:"Item usado para localizar strongholds e ativar portais do End.", tab:"items", section:"other", claims:["Eyes of Ender ajudam a localizar strongholds.","Eles são usados para completar os quadros de portal do End."], relationships:[] },
  { game:"Minecraft", name:"The End", type:"location", aliases:["End"], summary:"Dimensão associada ao Ender Dragon e aos Endermen.", tab:"maps", section:"regions", claims:["The End é uma dimensão separada acessada por um portal do End."], relationships:[{type:"contains",target:"Ender Dragon"}] },
  { game:"Minecraft", name:"Diamond Sword", type:"weapon", aliases:["Espada de Diamante","Diamond sword"], summary:"Arma corpo a corpo criada com diamantes e um graveto.", tab:"items", section:"weapons", claims:["A receita tradicional da Diamond Sword usa dois diamantes e um graveto em uma Crafting Table."], relationships:[{type:"requires",target:"Diamond"},{type:"requires",target:"Stick"}] },
  { game:"Minecraft", name:"Diamond", type:"material", aliases:["Diamante"], summary:"Recurso mineral usado em ferramentas, armas, armaduras e outros itens.", tab:"items", section:"materials", claims:["Diamonds são usados na criação de equipamentos de alto nível, incluindo a Diamond Sword."], relationships:[] },
  { game:"Minecraft", name:"Stick", type:"material", aliases:["Graveto"], summary:"Componente básico usado em diversas receitas de ferramentas e armas.", tab:"items", section:"materials", claims:["Sticks são componentes comuns em receitas de ferramentas e armas."], relationships:[] },
  { game:"Minecraft", name:"Ancient City", type:"location", aliases:["Cidade Ancestral"], summary:"Estrutura rara gerada em regiões do Deep Dark e ligada ao Warden e a loot específico.", tab:"guides", section:"locations", claims:["Ancient Cities são estruturas encontradas no Deep Dark.","Explorar uma Ancient City exige cuidado com sensores sculk e a possibilidade de invocar o Warden."], relationships:[{type:"located_in",target:"Deep Dark"},{type:"related_to",target:"Warden"}] },
  { game:"Minecraft", name:"Deep Dark", type:"biome", aliases:["Escuridão Profunda"], summary:"Bioma subterrâneo com blocos sculk e risco de encontro com o Warden.", tab:"maps", section:"regions", claims:["O Deep Dark é um bioma subterrâneo associado a blocos sculk e Ancient Cities."], relationships:[{type:"contains",target:"Ancient City"}] },
  { game:"Minecraft", name:"Warden", type:"mob", aliases:[], summary:"Mob extremamente perigoso ligado ao Deep Dark e a shriekers sculk.", tab:"mobs", section:"hostile", claims:["O Warden pode surgir após a ativação repetida de Sculk Shriekers em condições apropriadas."], relationships:[{type:"appears_in",target:"Deep Dark"}] },
  { game:"Minecraft", name:"Creeper", type:"mob", aliases:[], summary:"Mob hostil conhecido por se aproximar silenciosamente e explodir perto do jogador.", tab:"mobs", section:"hostile", claims:["Creepers explodem quando chegam perto do jogador após iniciar seu tempo de detonação."], relationships:[] },
  { game:"Minecraft", name:"Ender Dragon", type:"boss", aliases:["Dragão do End"], summary:"Chefe principal encontrado na ilha central do End.", tab:"mobs", section:"bosses", claims:["O Ender Dragon é enfrentado na dimensão The End e sua luta envolve End Crystals que podem recuperar sua vida."], relationships:[{type:"appears_in",target:"The End"}] },
  { game:"Minecraft", name:"Ancient Builder Theory", type:"theory", aliases:["Teoria dos Construtores Antigos","Ancient Builders"], summary:"Teoria comunitária que tenta ligar antigas construções e a origem de certas criaturas do universo Minecraft.", tab:"lore", section:"theories", canon:"THEORY", claims:["A ideia de que uma civilização de Ancient Builders explica a origem dos Endermen é uma teoria da comunidade, não uma origem oficialmente confirmada."], relationships:[{type:"related_to",target:"Enderman"}] },

  // Fortnite
  { game:"Fortnite", name:"Battle Royale", type:"mode", aliases:["BR"], summary:"Modo competitivo em que jogadores buscam sobreviver até restar um vencedor ou equipe.", tab:"gameplay", section:"mechanics", claims:["No Battle Royale, jogadores coletam equipamentos enquanto a área segura diminui ao longo da partida."], relationships:[{type:"uses",target:"Storm"}] },
  { game:"Fortnite", name:"Storm", type:"mechanic", aliases:["Tempestade"], summary:"Mecânica que restringe progressivamente a área segura durante partidas Battle Royale.", tab:"gameplay", section:"mechanics", claims:["A Storm força os jogadores a se moverem para zonas seguras cada vez menores."], relationships:[] },
  { game:"Fortnite", name:"Battle Bus", type:"vehicle", aliases:["Ônibus de Batalha"], summary:"Veículo de início de partida do qual os jogadores saltam para escolher a área de pouso.", tab:"gameplay", section:"mechanics", claims:["Jogadores começam partidas Battle Royale no Battle Bus e escolhem quando saltar."], relationships:[] },
  { game:"Fortnite", name:"Building", type:"mechanic", aliases:["Construção","Build"], summary:"Sistema clássico de criação rápida de estruturas usando materiais coletados.", tab:"gameplay", section:"mechanics", claims:["Em modos com construção habilitada, jogadores podem erguer estruturas para mobilidade, cobertura e controle de espaço."], relationships:[] },
  { game:"Fortnite", name:"Zero Build", type:"mode", aliases:["Construção Zero"], summary:"Variação do Battle Royale que remove a construção tradicional.", tab:"gameplay", section:"mechanics", claims:["Zero Build remove a construção tradicional e enfatiza cobertura, movimento e posicionamento."], relationships:[] },

  // CS2
  { game:"Counter-Strike 2", name:"AK-47", type:"weapon", aliases:["AK47"], summary:"Rifle disponível para o lado Terrorista e conhecido por alto poder de dano.", tab:"weapons", section:"primary", claims:["A AK-47 é um rifle do lado Terrorista e recompensa precisão e controle de recoil."], relationships:[] },
  { game:"Counter-Strike 2", name:"AWP", type:"weapon", aliases:[], summary:"Rifle de precisão de alto impacto usado para controlar ângulos e linhas longas.", tab:"weapons", section:"primary", claims:["A AWP é uma arma de precisão cara e de alto impacto, normalmente usada para controlar linhas de visão."], relationships:[] },
  { game:"Counter-Strike 2", name:"Mirage", type:"map", aliases:[], summary:"Mapa competitivo com bombsites A e B e forte disputa por controle do meio.", tab:"maps", section:"locations", claims:["Mirage possui dois bombsites e uma região central importante para rotação e controle de mapa."], relationships:[] },
  { game:"Counter-Strike 2", name:"Economy", type:"mechanic", aliases:["Economia"], summary:"Sistema de dinheiro que influencia compras de armas, utilitários e equipamentos a cada round.", tab:"gameplay", section:"strategy", claims:["Decisões de compra dependem do dinheiro disponível e podem afetar vários rounds consecutivos."], relationships:[] },
  { game:"Counter-Strike 2", name:"Premier", type:"rank_system", aliases:["Premier Mode"], summary:"Modo competitivo com sistema de rating e escolha de mapas por veto.", tab:"ranks", section:"system", claims:["Premier usa um sistema de rating e um processo de veto de mapas antes da partida."], relationships:[] },

  // Roblox
  { game:"Roblox", name:"Experience", type:"concept", aliases:["Experiência","Roblox game"], summary:"Nome usado na plataforma para mundos e jogos criados por desenvolvedores e comunidades.", tab:"experiences", section:"featured", claims:["Roblox hospeda experiências criadas por usuários que podem variar amplamente em gênero e mecânicas."], relationships:[] },
  { game:"Roblox", name:"Roblox Studio", type:"tool", aliases:["Studio"], summary:"Ambiente de criação usado para desenvolver experiências Roblox.", tab:"gameplay", section:"mechanics", claims:["Roblox Studio é a ferramenta principal de criação de experiências na plataforma."], relationships:[{type:"uses",target:"Luau"}] },
  { game:"Roblox", name:"Luau", type:"technology", aliases:["Lua Roblox"], summary:"Linguagem usada para scripts em experiências Roblox, derivada de Lua e desenvolvida para a plataforma.", tab:"gameplay", section:"mechanics", claims:["Luau é a linguagem de scripting usada no ecossistema Roblox."], relationships:[] },
  { game:"Roblox", name:"Robux", type:"currency", aliases:[], summary:"Moeda virtual do ecossistema Roblox usada em compras e transações compatíveis com a plataforma.", tab:"items", section:"other", claims:["Robux é a moeda virtual usada em várias compras dentro do ecossistema Roblox."], relationships:[] },

  // GTA V
  { game:"Grand Theft Auto V", name:"Michael De Santa", type:"character", aliases:["Michael"], summary:"Um dos três protagonistas jogáveis da campanha de GTA V.", tab:"characters", section:"main", claims:["Michael é um dos três protagonistas centrais da história principal de GTA V."], relationships:[{type:"associated_with",target:"Los Santos"}] },
  { game:"Grand Theft Auto V", name:"Franklin Clinton", type:"character", aliases:["Franklin"], summary:"Um dos três protagonistas jogáveis da campanha de GTA V.", tab:"characters", section:"main", claims:["Franklin é um dos três protagonistas centrais da história principal de GTA V."], relationships:[{type:"associated_with",target:"Los Santos"}] },
  { game:"Grand Theft Auto V", name:"Trevor Philips", type:"character", aliases:["Trevor"], summary:"Um dos três protagonistas jogáveis da campanha de GTA V.", tab:"characters", section:"main", claims:["Trevor é um dos três protagonistas centrais da história principal de GTA V."], relationships:[] },
  { game:"Grand Theft Auto V", name:"Los Santos", type:"location", aliases:[], summary:"Cidade principal de GTA V, cercada por outras áreas de Blaine County.", tab:"maps", section:"regions", claims:["Los Santos é a principal área urbana de GTA V."], relationships:[] },
  { game:"Grand Theft Auto V", name:"Heists", type:"mechanic", aliases:["Assaltos"], summary:"Missões de grande escala que envolvem preparação, escolhas e execução de operações complexas.", tab:"missions", section:"main", claims:["Heists combinam etapas de preparação e execução dentro da progressão de GTA V e GTA Online."], relationships:[] },
  { game:"Grand Theft Auto V", name:"Wanted Level", type:"mechanic", aliases:["Nível de Procurado","Estrelas"], summary:"Sistema que representa a intensidade da perseguição das forças policiais ao jogador.", tab:"gameplay", section:"mechanics", claims:["O Wanted Level aumenta conforme certas ações chamam atenção das autoridades e pode escalar a resposta policial."], relationships:[] },

  // Sonic franchise shared basics attached to first game where useful
  { game:"Sonic the Hedgehog", name:"Sonic", type:"character", aliases:["Sonic the Hedgehog"], summary:"O protagonista veloz da série, associado à coleta de anéis e fases de alta velocidade.", tab:"characters", section:"main", claims:["Sonic é o protagonista da série e sua jogabilidade clássica enfatiza velocidade, momentum e plataformas."], relationships:[{type:"enemy_of",target:"Dr. Eggman"}] },
  { game:"Sonic the Hedgehog", name:"Dr. Eggman", type:"character", aliases:["Doctor Eggman","Dr. Robotnik","Robotnik"], summary:"Principal antagonista recorrente da série Sonic.", tab:"characters", section:"villains", claims:["Dr. Eggman é um antagonista recorrente e frequentemente usa máquinas e robôs contra Sonic."], relationships:[] },
  { game:"Sonic the Hedgehog", name:"Green Hill Zone", type:"location", aliases:["Green Hill"], summary:"Zona inicial icônica do primeiro Sonic the Hedgehog.", tab:"stages", section:"zones", claims:["Green Hill Zone é a primeira zona do Sonic the Hedgehog original."], relationships:[] },
  { game:"Sonic the Hedgehog 2", name:"Tails", type:"character", aliases:["Miles Prower"], summary:"Aliado de Sonic introduzido em Sonic the Hedgehog 2.", tab:"characters", section:"allies", claims:["Tails foi introduzido em Sonic the Hedgehog 2 como parceiro de Sonic."], relationships:[{type:"ally_of",target:"Sonic"}] },

  // Spider-Man
  { game:"Marvel's Spider-Man", name:"Peter Parker", type:"character", aliases:["Spider-Man","Homem-Aranha"], summary:"Protagonista principal do primeiro jogo da série da Insomniac.", tab:"characters", section:"main", claims:["Peter Parker é o Spider-Man jogável central de Marvel's Spider-Man."], relationships:[] },
  { game:"Marvel's Spider-Man", name:"Web Swinging", type:"mechanic", aliases:["Balanço de Teia","Web-swinging"], summary:"Sistema principal de deslocamento pela cidade usando teias e momentum.", tab:"gameplay", section:"mechanics", claims:["O web swinging é uma das principais formas de locomoção pela cidade."], relationships:[] },
  { game:"Marvel's Spider-Man: Miles Morales", name:"Miles Morales", type:"character", aliases:["Miles","Spider-Man Miles"], summary:"Protagonista de Marvel's Spider-Man: Miles Morales, com habilidades próprias além dos poderes tradicionais do Spider-Man.", tab:"characters", section:"main", claims:["Miles Morales é o protagonista jogável de Marvel's Spider-Man: Miles Morales."], relationships:[] },

  // General GTA history entities
  { game:"Grand Theft Auto: San Andreas", name:"Carl Johnson", type:"character", aliases:["CJ"], summary:"Protagonista de Grand Theft Auto: San Andreas.", tab:"characters", section:"main", claims:["Carl 'CJ' Johnson é o protagonista de Grand Theft Auto: San Andreas."], relationships:[] },
  { game:"Grand Theft Auto IV", name:"Niko Bellic", type:"character", aliases:["Niko"], summary:"Protagonista de Grand Theft Auto IV.", tab:"characters", section:"main", claims:["Niko Bellic é o protagonista de Grand Theft Auto IV."], relationships:[] }
];

export const GAME_KNOWLEDGE_SEEDS = [
  { game:"Minecraft", title:"Gameplay de Minecraft", tab:"gameplay", section:"mechanics", summary:"A experiência combina coleta de recursos, crafting, construção, exploração e combate. Survival adiciona vida, fome e progressão de equipamentos, enquanto Creative prioriza construção livre.", topics:["gameplay","mechanics"], claims:["Minecraft organiza grande parte da progressão de Survival em coleta de recursos, crafting, exploração e melhoria de equipamentos.","Creative oferece recursos livres e voo para construção e experimentação."] },
  { game:"Fortnite", title:"Gameplay do Battle Royale", tab:"gameplay", section:"mechanics", summary:"Partidas começam com queda no mapa, coleta de equipamentos e movimentação para zonas seguras enquanto a Storm fecha a área jogável.", topics:["gameplay","battle royale"], claims:["A Storm reduz a área segura durante partidas Battle Royale.","Loot, posicionamento e rotação entre zonas são partes centrais da partida."] },
  { game:"Roblox", title:"Como Roblox funciona", tab:"gameplay", section:"mechanics", summary:"Roblox é uma plataforma: cada experiência pode ter regras, progressão, economia e controles próprios, enquanto contas e avatares pertencem ao ecossistema Roblox.", topics:["gameplay","platform"], claims:["Experiências Roblox são criadas por desenvolvedores usando Roblox Studio e podem implementar sistemas próprios."] },
  { game:"Counter-Strike 2", title:"Estrutura de uma partida competitiva", tab:"gameplay", section:"mechanics", summary:"Counter-Strike 2 é dividido em rounds. Terroristas e Contra-Terroristas disputam objetivos, e a economia de cada round influencia armas, armadura e utilitários disponíveis.", topics:["gameplay","competitive","economy"], claims:["O modo competitivo usa rounds e objetivos de equipe.","A economia influencia o equipamento que cada jogador pode comprar antes dos rounds."] },
  { game:"Sonic the Hedgehog", title:"Gameplay clássico de Sonic", tab:"gameplay", section:"mechanics", summary:"O jogo combina plataformas com velocidade e momentum. Rings funcionam como proteção contra dano enquanto também servem como colecionáveis.", topics:["gameplay","platformer"], claims:["Rings protegem Sonic de perder uma vida imediatamente quando ele recebe dano, desde que carregue pelo menos um ring."] },
  { game:"Sonic the Hedgehog 2", title:"O que Sonic 2 acrescenta", tab:"gameplay", section:"mechanics", summary:"Sonic 2 mantém o foco em velocidade e plataformas, adiciona Tails e introduz o Spin Dash como ferramenta importante de aceleração.", topics:["gameplay","platformer"], claims:["Sonic 2 introduziu Tails e o Spin Dash na série principal clássica."] },
  { game:"Sonic the Hedgehog 3", title:"Escudos e exploração em Sonic 3", tab:"gameplay", section:"mechanics", summary:"Sonic 3 amplia a exploração com rotas alternativas e escudos elementais que oferecem propriedades diferentes durante as fases.", topics:["gameplay","platformer"], claims:["Sonic 3 apresenta escudos elementais com efeitos distintos para movimentação e proteção."] },
  { game:"Sonic 3 & Knuckles", title:"Campanha combinada", tab:"story", section:"main", summary:"A experiência combinada conecta Sonic 3 e Sonic & Knuckles em uma campanha contínua e amplia personagens jogáveis, rotas e fases.", topics:["story","gameplay"], claims:["Sonic 3 & Knuckles combina o conteúdo conectado de Sonic 3 e Sonic & Knuckles em uma campanha maior."] },
  { game:"Marvel's Spider-Man", title:"Movimentação e combate", tab:"gameplay", section:"mechanics", summary:"A exploração usa web swinging, parkour e pontos de impulso; o combate mistura esquiva, ataques aéreos, gadgets e uso do cenário.", topics:["gameplay","movement","combat"], claims:["Web swinging é a principal forma de atravessar rapidamente a cidade.","O combate combina ataques corpo a corpo, esquiva, gadgets e interação com objetos do ambiente."] },
  { game:"Marvel's Spider-Man: Miles Morales", title:"Poderes de Miles", tab:"abilities", section:"core", summary:"Miles combina habilidades tradicionais do Spider-Man com Venom powers bioelétricos e camuflagem, criando opções próprias de combate e furtividade.", topics:["abilities","combat"], claims:["Miles possui habilidades bioelétricas conhecidas como Venom powers e pode usar camuflagem em gameplay."] },
  { game:"Marvel's Spider-Man 2", title:"Dois Spider-Men jogáveis", tab:"gameplay", section:"mechanics", summary:"A campanha utiliza Peter Parker e Miles Morales como heróis jogáveis, cada um com habilidades e árvores de progressão próprias e compartilhadas.", topics:["gameplay","characters"], claims:["Peter Parker e Miles Morales são jogáveis ao longo da campanha de Marvel's Spider-Man 2."] },
  { game:"Grand Theft Auto III", title:"Liberty City em 3D", tab:"gameplay", section:"mechanics", summary:"GTA III estruturou a fórmula 3D de mundo aberto da série com direção, combate, missões e exploração livre de Liberty City.", topics:["gameplay","open world"], claims:["GTA III combina missões estruturadas com exploração livre de Liberty City."] },
  { game:"Grand Theft Auto: Vice City", title:"Vice City e Tommy Vercetti", tab:"story", section:"main", summary:"A história acompanha Tommy Vercetti em Vice City, enquanto o jogador expande sua influência por missões e aquisição de propriedades.", topics:["story","character"], claims:["Tommy Vercetti é o protagonista de Grand Theft Auto: Vice City."] },
  { game:"Grand Theft Auto: San Andreas", title:"San Andreas e progressão de CJ", tab:"gameplay", section:"progression", summary:"San Andreas amplia a fórmula de mundo aberto com atributos do personagem, customização, veículos variados e uma região extensa conectando Los Santos, San Fierro e Las Venturas.", topics:["gameplay","progression","open world"], claims:["A progressão de CJ inclui atributos e customização além da estrutura tradicional de missões."] },
  { game:"Grand Theft Auto IV", title:"Niko e Liberty City", tab:"story", section:"main", summary:"A história acompanha Niko Bellic em Liberty City e explora suas relações, trabalhos e conflitos enquanto ele procura construir uma nova vida.", topics:["story","character"], claims:["Niko Bellic é o protagonista principal de Grand Theft Auto IV."] },
  { game:"Grand Theft Auto V", title:"Três protagonistas", tab:"story", section:"main", summary:"A campanha alterna entre Michael De Santa, Franklin Clinton e Trevor Philips, conectando suas histórias em missões e grandes assaltos.", topics:["story","characters"], claims:["GTA V possui três protagonistas centrais jogáveis: Michael, Franklin e Trevor."] },
  { game:"Grand Theft Auto VI", title:"Conhecimento volátil de GTA VI", tab:"overview", section:"details", summary:"GameIndex trata detalhes de GTA VI que podem mudar com o tempo como conhecimento que exige revalidação em fontes atuais antes de ser exibido como definitivo.", topics:["release","current information"], status:"UNVERIFIED", confidence:.45, claims:["Datas, plataformas e outros detalhes de lançamento de GTA VI devem ser revalidados em fontes atuais antes de serem promovidos para CURRENT."] }
];

export const ENTITY_KNOWLEDGE_SEEDS = [
  { game:"Minecraft", entity:"Enderman", title:"Origem dos Endermen — o que é oficial", tab:"lore", section:"official", canon:"UNKNOWN", confidence:.74, summary:"O GameIndex não trata uma origem específica dos Endermen como oficialmente confirmada. Explicações como a teoria dos Ancient Builders pertencem à comunidade e devem permanecer identificadas como teoria.", topics:["lore","origin","enderman"], claims:["Uma origem específica dos Endermen não é tratada pelo pacote base como confirmação oficial.","A ideia de que Ancient Builders se tornaram Endermen deve ser classificada como THEORY, não como fato oficial."] },
  { game:"Minecraft", entity:"Enderman", title:"Teorias populares sobre Endermen", tab:"lore", section:"theories", canon:"THEORY", confidence:.66, summary:"A comunidade criou várias hipóteses para explicar os Endermen. Uma das mais conhecidas relaciona a criatura a uma antiga civilização de construtores, mas essa interpretação não é cânone confirmado.", topics:["lore","theory","enderman"], claims:["A teoria dos Ancient Builders é uma interpretação comunitária sem confirmação oficial como origem dos Endermen."] }
];
