import { currentAuth } from "../auth/auth-service.mjs";
import { requireAdmin, adminSession } from "../admin/admin-auth.mjs";
import { discoveryFacets, discoveryGamesPage, recommendGames } from "../recommendations/recommendation-service.mjs";
import { clearRecommendationHistory, recordInterestSignal, recordRecommendationEvent, recommendationsEnabled, setRecommendationsEnabled } from "../database/repositories/interest-repository.mjs";
import { getGameById, getGameBySlug } from "../database/repositories/game-repository.mjs";
import { db } from "../database/connection.mjs";
import { gamePublicVisual } from "../images/public-visual.mjs";
import { getImage3Asset, getImage3Binary, image3AssetDetail, imageEngine3Summary } from "../images/image-engine3.mjs";

function sessionUser(req){return currentAuth(req)?.user||null;}
function publicGame(row){return {id:row.game.id,slug:row.game.slug,nome:row.game.nome,descricao:row.game.descricao,generos:row.game.generos,plataformas:row.game.plataformas,franquia:row.game.franquia,visual:gamePublicVisual(row.game),score:Math.round(row.score*10)/10,reason:row.reason,personalized:row.personalized};}
function publicAsset(asset){return asset?{id:asset.id,gameId:asset.gameId,entityId:asset.entityId,imageRole:asset.imageRole,state:asset.state,currentRevision:asset.currentRevision,browserStatus:asset.browserStatus,ready:asset.ready,publicPath:asset.publicPath,url:asset.publicPath,engine:"IMAGE_ENGINE_3"}:null;}
function listV3(gameId,{limit=100,offset=0}={}){const rows=db.prepare(`SELECT id FROM ie3_assets WHERE game_id=? AND current_revision>0 ORDER BY CASE state WHEN 'READY' THEN 0 ELSE 1 END,updated_at DESC LIMIT ? OFFSET ?`).all(gameId,Math.min(200,Math.max(1,Number(limit)||100)),Math.max(0,Number(offset)||0));return rows.map(r=>publicAsset(getImage3Asset(r.id))).filter(Boolean);}
export function registerBeta07Routes(app){
  app.get("/api/beta0705/status",(req,res)=>res.json({version:"Beta 0.986",codename:"Production Consolidation",navigationRecovery:"ACTIVE",imageRuntime:"IMAGE_ENGINE_3_NATIVE",admin:Boolean(adminSession(req))}));
  app.get("/api/beta07/status",(req,res)=>res.json({version:"Beta 0.986",codename:"Production Consolidation",intelligence:"GI_CORE_SCRIPTS_PLUS_OPTIONAL_DEXTER",autoPageBuilder:String(process.env.GAMEVAULT_PAGE_GENERATION_ENABLED??"true").toLowerCase()==="true"?"ACTIVE":"OFFLINE",imageRuntime:"IMAGE_ENGINE_3_NATIVE",recommendations:"ACTIVE",gamesCatalog:"ACTIVE",admin:Boolean(adminSession(req))}));
  app.get("/api/discovery/home",(req,res)=>{const user=sessionUser(req),result=recommendGames({userId:user?.id||null,limit:req.query.limit||10,record:true});res.json({mode:result.mode,personalized:result.personalized,entries:result.entries.map(publicGame)});});
  app.get("/api/discovery/games",(req,res)=>{const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(48,Math.max(1,Number(req.query.limit)||24));const result=discoveryGamesPage({q:req.query.q||"",genre:req.query.genre||"",platform:req.query.platform||"",franchise:req.query.franchise||"",sort:req.query.sort||"community",limit,offset:(page-1)*limit});res.setHeader("Cache-Control","public, max-age=30, stale-while-revalidate=120");res.json({entries:result.entries.map(game=>({...game,visual:gamePublicVisual(game)})),total:result.total,page,limit,pages:Math.max(1,Math.ceil(result.total/limit))});});
  app.get("/api/discovery/facets",(req,res)=>{res.setHeader("Cache-Control","public, max-age=300, stale-while-revalidate=900");res.json(discoveryFacets());});
  app.get("/api/personalization",(req,res)=>{const user=sessionUser(req);if(!user)return res.json({authenticated:false,recommendationsEnabled:false});res.json({authenticated:true,recommendationsEnabled:recommendationsEnabled(user.id)});});
  app.post("/api/personalization",(req,res)=>{const user=sessionUser(req);if(!user)return res.status(401).json({erro:"Faça login para alterar a personalização."});res.json({recommendationsEnabled:setRecommendationsEnabled(user.id,Boolean(req.body?.recommendationsEnabled))});});
  app.delete("/api/personalization/history",(req,res)=>{const user=sessionUser(req);if(!user)return res.status(401).json({erro:"Faça login para limpar as recomendações."});res.json({ok:true,...clearRecommendationHistory(user.id)});});
  app.post("/api/discovery/event",(req,res)=>{const user=sessionUser(req);if(!user)return res.status(204).end();const game=getGameById(req.body?.gameId)||getGameBySlug(req.body?.gameSlug||"");if(!game)return res.status(404).json({erro:"Jogo não encontrado."});const event=String(req.body?.eventType||"VIEW_GAME").toUpperCase(),allowed=new Set(["VIEW_GAME","SEARCH_GAME","DISMISS_RECOMMENDATION","RECOMMENDATION_CLICK"]);if(!allowed.has(event))return res.status(400).json({erro:"Sinal de descoberta inválido."});recordInterestSignal({userId:user.id,gameId:game.id,genre:game.generos?.[0]||"",franchise:game.franquia||"",signalType:event,weight:event==="DISMISS_RECOMMENDATION"?-45:event==="RECOMMENDATION_CLICK"?9:event==="VIEW_GAME"?14:10});recordRecommendationEvent({userId:user.id,gameId:game.id,eventType:event==="DISMISS_RECOMMENDATION"?"DISMISS":event==="RECOMMENDATION_CLICK"?"CLICK":"ACTIVITY",reason:"USER_SIGNAL"});res.json({ok:true});});

  // HF2 compatibility: old /api/images URLs expose only Image Engine 3 assets.
  app.get("/api/images/:id",(req,res)=>{const asset=getImage3Asset(req.params.id);if(!asset)return res.status(404).json({erro:"Ativo Image Engine 3 não encontrado."});res.json(publicAsset(asset));});
  app.get("/api/images/:id/content",(req,res)=>{const asset=getImage3Asset(req.params.id);if(!asset?.currentRevision)return res.status(404).json({erro:"Ativo persistente não encontrado."});const binary=getImage3Binary(asset.id,asset.currentRevision);if(!binary)return res.status(404).json({erro:"Revisão persistente não encontrada."});res.setHeader("Content-Type",binary.mimeType);res.setHeader("Content-Length",String(binary.byteSize));res.setHeader("Cache-Control","public, max-age=31536000, immutable");res.setHeader("ETag",`"${binary.checksum}"`);res.setHeader("X-Content-Type-Options","nosniff");res.send(Buffer.from(binary.bytes));});
  app.get("/api/games/:gameId/images",(req,res)=>{const game=getGameById(req.params.gameId)||getGameBySlug(req.params.gameId);if(!game)return res.status(404).json({erro:"Jogo não encontrado."});res.json({engine:"IMAGE_ENGINE_3",entries:listV3(game.id,{limit:req.query.limit||100,offset:req.query.offset||0})});});
  app.get("/api/admin/images",requireAdmin,(req,res)=>{const gameId=req.query.gameId?String(req.query.gameId):null;const rows=gameId?listV3(gameId,{limit:req.query.limit||100,offset:req.query.offset||0}):db.prepare(`SELECT id FROM ie3_assets WHERE current_revision>0 ORDER BY updated_at DESC LIMIT ? OFFSET ?`).all(Math.min(200,Number(req.query.limit)||100),Math.max(0,Number(req.query.offset)||0)).map(r=>publicAsset(getImage3Asset(r.id)));res.json({engine:"IMAGE_ENGINE_3",entries:rows,metrics:imageEngine3Summary()});});
  app.get("/api/admin/images/:id",requireAdmin,(req,res)=>{const asset=image3AssetDetail(req.params.id);if(!asset)return res.status(404).json({erro:"Ativo não encontrado."});res.json({engine:"IMAGE_ENGINE_3",asset});});
  app.post("/api/admin/images/:id/status",requireAdmin,(req,res)=>res.status(410).json({ok:false,error:{code:"LEGACY_IMAGE_STATUS_REMOVED",message:"A aprovação manual do sistema antigo foi removida. Image Engine 3 valida e repara automaticamente."}}));
}
