import { randomUUID } from "node:crypto";
import { db, schemaVersion, storageOrigin } from "../database/connection.mjs";
import { gameCount, getGameBySlug } from "../database/repositories/game-repository.mjs";
import { pageCount, getPageById, listPageValidations, setPageStatus } from "../database/repositories/page-repository.mjs";
import { currentAuth } from "../auth/auth-service.mjs";
import { devAccessSnapshot } from "../admin/dev-access.mjs";
import { runConstructionPreflight } from "../construction/construction-preflight.mjs";
import { scheduleConstructionRun } from "../construction/construction-runner.mjs";
import {
  createBlockedConstructionRun,createConstructionRun,getConstructionItem,getConstructionRun,listConstructionAttempts,listConstructionEvents,listConstructionItems,listConstructionRuns,
  requestConstructionCancel,requestConstructionPause,resetConstructionItem,resetFailedConstructionItems,resumeConstructionRun,runIsTerminal,updateConstructionRun
} from "../database/repositories/construction-repository.mjs";

function requestId(req){return String(req.headers?.["x-request-id"]||randomUUID()).slice(0,120);}
function sendError(res,status,{requestId:id,code="CONSTRUCTION_FAILED",message="A construção não pôde continuar.",component="CONSTRUCTION_API",retryable=false,suggestedAction="Abra o diagnóstico DEV."}={}){return res.status(status).json({ok:false,error:{requestId:id,code,message,component,retryable:Boolean(retryable),suggestedAction}});}
function safeRun(run){if(!run)return null;const {idempotencyKey,leaseOwner,leaseExpiresAt,...safe}=run;return safe;}
function access(req,res){const id=requestId(req),auth=currentAuth(req);if(!auth){sendError(res,401,{requestId:id,code:"AUTH_REQUIRED",message:"Faça login para usar o Construction System.",component:"CONSTRUCTION_AUTH",suggestedAction:"Entre novamente na conta Franchesco01."});return null;}const snapshot=devAccessSnapshot(req,"PAGE_GENERATION");if(!snapshot.authorized){sendError(res,403,{requestId:id,code:"CONSTRUCTION_PERMISSION_DENIED",message:"ADMIN + DEV e page_generation são obrigatórios.",component:"CONSTRUCTION_AUTH",suggestedAction:"Abra a recuperação ADMIN + DEV."});return null;}return {id,auth,snapshot};}
function owned(req,res,runId){const granted=access(req,res);if(!granted)return null;const run=getConstructionRun(runId);if(!run){sendError(res,404,{requestId:granted.id,code:"CONSTRUCTION_RUN_NOT_FOUND",message:"A execução não foi encontrada.",component:"CONSTRUCTION_API",suggestedAction:"Atualize a página do jogo."});return null;}if(run.userId&&run.userId!==granted.auth.user.id&&granted.snapshot.role!=="ADMIN"){sendError(res,403,{requestId:granted.id,code:"CONSTRUCTION_OWNERSHIP_DENIED",message:"Esta execução pertence a outra conta.",component:"CONSTRUCTION_AUTH",suggestedAction:"Use a conta que iniciou a construção."});return null;}return {...granted,run};}
function asyncBoundary(handler){return (req,res)=>Promise.resolve(handler(req,res)).catch(error=>sendError(res,500,{requestId:requestId(req),code:"CONSTRUCTION_INTERNAL_ERROR",message:"O servidor registrou um erro interno do Construction System.",component:"CONSTRUCTION_API",retryable:true,suggestedAction:`Copie o requestId e abra os eventos. ${String(error?.code||"").slice(0,80)}`}));}

export async function handleConstructionStart(req,res){
  const granted=req.gameIndexDevAccess?{id:requestId(req),auth:currentAuth(req),snapshot:req.gameIndexDevAccess}:access(req,res);if(!granted?.auth)return;
  const game=getGameBySlug(req.params.slug);if(!game)return sendError(res,404,{requestId:granted.id,code:"CONSTRUCTION_GAME_NOT_FOUND",message:"Jogo não encontrado.",component:"PREFLIGHT_GAME",suggestedAction:"Volte ao catálogo."});
  const demoMode=Boolean(req.body?.demoMode),language=String(req.body?.language||"pt-BR"),includeImages=req.body?.includeImages===true,researchMode=demoMode?"STANDARD":String(req.body?.researchMode||"DEEP").toUpperCase()==="STANDARD"?"STANDARD":"DEEP",publishMode="PREVIEW_ONLY";
  const preflight=runConstructionPreflight({game,userId:granted.auth.user.id,access:granted.snapshot,language,demoMode,maxEntities:demoMode?0:null});
  if(!preflight.ok){let blocked=null;try{if(preflight.error.code!=="CONSTRUCTION_DATABASE_READ_ONLY"&&preflight.error.code!=="CONSTRUCTION_STORAGE_UNAVAILABLE"&&preflight.error.code!=="CONSTRUCTION_ACTIVE_RUN_EXISTS")blocked=createBlockedConstructionRun({requestId:granted.id,userId:granted.auth.user.id,gameId:game.id,language,researchMode,publishMode,includeImages,demoMode,error:preflight.error});}catch{}return res.status(preflight.statusCode).json({ok:false,preflight,run:safeRun(blocked),error:{requestId:granted.id,...preflight.error}});}
  const run=createConstructionRun({requestId:granted.id,userId:granted.auth.user.id,gameId:game.id,language:preflight.language,researchMode,publishMode,includeImages,demoMode,plan:preflight.plan});if(!run.reused)scheduleConstructionRun(run.id);const publicRun=safeRun(run);return res.status(202).json({ok:true,reused:Boolean(run.reused),preflight,run:publicRun,job:publicRun,statusUrl:`/api/construction-runs/${run.id}`,itemsUrl:`/api/construction-runs/${run.id}/items`,eventsUrl:`/api/construction-runs/${run.id}/events`});
}

export function registerBeta092Routes(app,{generationLimiter}={}){
  const limit=generationLimiter||((req,res,next)=>next());
  app.get("/api/beta092/status",(req,res)=>{const counts={runs:0,active:0,completed:0,blockedSystemic:0};try{Object.assign(counts,db.prepare(`SELECT COUNT(*) runs,SUM(CASE WHEN status IN ('QUEUED','RUNNING','PAUSED','RETRY_SCHEDULED') THEN 1 ELSE 0 END) active,SUM(CASE WHEN status='COMPLETED' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN status='BLOCKED_SYSTEMIC' THEN 1 ELSE 0 END) blockedSystemic FROM construction_runs`).get());}catch{}res.json({product:"GameIndex",version:"Beta 0.92",semanticVersion:"0.92.0",codename:"Construction System",schema:schemaVersion(),games:gameCount(),pages:pageCount(),storageOrigin,apiKeyRequired:false,mode:"LOCAL_FIRST_NO_API_KEY",architecture:"RESEARCH_TO_BOSS_TO_CONSTRUCTION",visualPolicy:"NO_PEOPLE_NO_WOMEN",construction:{enabled:String(process.env.GAMEINDEX_CONSTRUCTION_ENABLED??process.env.GAMEINDEX_FULL_BUILD_ENABLED??"true").toLowerCase()!=="false",pagesFirst:true,imagesSeparate:true,...counts}});});
  app.get("/api/beta092/my-access",(req,res)=>{const granted=access(req,res);if(!granted)return;res.json({authenticated:true,user:{id:granted.auth.user.id,username:granted.auth.user.username||"",role:granted.snapshot.role,tier:granted.snapshot.tier},construction:granted.snapshot,pageGeneration:granted.snapshot,imageManagement:devAccessSnapshot(req,"IMAGE_DIAGNOSTICS")});});
  app.post("/api/games/:slug/construction/preflight",limit,asyncBoundary(async(req,res)=>{const granted=access(req,res);if(!granted)return;const game=getGameBySlug(req.params.slug),preflight=runConstructionPreflight({game,userId:granted.auth.user.id,access:granted.snapshot,language:req.body?.language||"pt-BR",demoMode:Boolean(req.body?.demoMode),maxEntities:req.body?.demoMode?0:null});if(!preflight.ok)return res.status(preflight.statusCode).json({ok:false,preflight,error:{requestId:granted.id,...preflight.error}});res.json({ok:true,requestId:granted.id,preflight});}));
  app.post("/api/games/:slug/construction/start",limit,asyncBoundary(handleConstructionStart));
  app.get("/api/games/:slug/construction/status",asyncBoundary(async(req,res)=>{const granted=access(req,res);if(!granted)return;const game=getGameBySlug(req.params.slug);if(!game)return sendError(res,404,{requestId:granted.id,code:"CONSTRUCTION_GAME_NOT_FOUND",message:"Jogo não encontrado.",component:"CONSTRUCTION_API"});const runs=listConstructionRuns({gameId:game.id,userId:granted.auth.user.id,language:req.query.lang||"pt-BR",limit:10}).map(safeRun),active=runs.find(run=>!runIsTerminal(run.status))||null;res.json({ok:true,game:{id:game.id,slug:game.slug,name:game.nome},runs,active});}));
  app.get("/api/construction-runs/:id",asyncBoundary(async(req,res)=>{const granted=owned(req,res,req.params.id);if(!granted)return;res.json({ok:true,run:safeRun(granted.run)});}));
  app.get("/api/construction-runs/:id/items",asyncBoundary(async(req,res)=>{const granted=owned(req,res,req.params.id);if(!granted)return;res.json({ok:true,run:safeRun(granted.run),items:listConstructionItems(granted.run.id).map(item=>({...item,attemptHistory:listConstructionAttempts(item.id)}))});}));
  app.get("/api/construction-runs/:id/events",asyncBoundary(async(req,res)=>{const granted=owned(req,res,req.params.id);if(!granted)return;res.json({ok:true,run:safeRun(granted.run),events:listConstructionEvents(granted.run.id,{after:req.query.after||0,limit:req.query.limit||500})});}));
  app.post("/api/construction-runs/:id/pause",limit,asyncBoundary(async(req,res)=>{const granted=owned(req,res,req.params.id);if(!granted)return;res.json({ok:true,run:safeRun(requestConstructionPause(granted.run.id))});}));
  app.post("/api/construction-runs/:id/resume",limit,asyncBoundary(async(req,res)=>{const granted=owned(req,res,req.params.id);if(!granted)return;const run=resumeConstructionRun(granted.run.id);scheduleConstructionRun(run.id);res.status(202).json({ok:true,run:safeRun(run)});}));
  app.post("/api/construction-runs/:id/cancel",limit,asyncBoundary(async(req,res)=>{const granted=owned(req,res,req.params.id);if(!granted)return;res.json({ok:true,run:safeRun(requestConstructionCancel(granted.run.id))});}));
  app.post("/api/construction-runs/:id/retry-failed",limit,asyncBoundary(async(req,res)=>{const granted=owned(req,res,req.params.id);if(!granted)return;const run=resetFailedConstructionItems(granted.run.id);scheduleConstructionRun(run.id);res.status(202).json({ok:true,run:safeRun(run)});}));
  app.post("/api/construction-items/:id/retry",limit,asyncBoundary(async(req,res)=>{const item=getConstructionItem(req.params.id);if(!item)return sendError(res,404,{requestId:requestId(req),code:"CONSTRUCTION_ITEM_NOT_FOUND",message:"Item não encontrado.",component:"CONSTRUCTION_API"});const granted=owned(req,res,item.runId);if(!granted)return;const reset=resetConstructionItem(item.id);updateConstructionRun(item.runId,{status:"RETRY_SCHEDULED",currentStage:"ITEM_RETRY"});scheduleConstructionRun(item.runId);res.status(202).json({ok:true,item:reset,run:safeRun(getConstructionRun(item.runId))});}));
  app.post("/api/construction-items/:id/retry-image",limit,asyncBoundary(async(req,res)=>{const item=getConstructionItem(req.params.id);if(!item)return sendError(res,404,{requestId:requestId(req),code:"CONSTRUCTION_ITEM_NOT_FOUND",message:"Item não encontrado.",component:"CONSTRUCTION_API"});const granted=owned(req,res,item.runId);if(!granted)return;const reset=resetConstructionItem(item.id,{imageOnly:true});updateConstructionRun(item.runId,{status:"RETRY_SCHEDULED",currentStage:"IMAGE_RETRY"});scheduleConstructionRun(item.runId);res.status(202).json({ok:true,item:reset,run:safeRun(getConstructionRun(item.runId))});}));
  app.post("/api/construction-runs/:id/publish",limit,asyncBoundary(async(req,res)=>{const granted=owned(req,res,req.params.id);if(!granted)return;let published=0,blocked=0;for(const item of listConstructionItems(granted.run.id)){if(!item.resultPageId)continue;const page=getPageById(item.resultPageId),checks=listPageValidations(item.resultPageId),required=new Set(["FACT_SAFETY","SOURCE_SAFETY","CONTEXT_SAFETY"]),pass=[...required].every(type=>checks.some(check=>check.type===type&&check.result==="PASS"));if(page&&pass&&new Set(["READY","NEEDS_REVIEW"]).has(page.status)){setPageStatus(page.id,"PUBLISHED");published++;}else blocked++;}res.json({ok:true,published,blocked,run:safeRun(getConstructionRun(granted.run.id))});}));
  app.get("/api/construction-runs/:id/diagnostic",asyncBoundary(async(req,res)=>{const granted=owned(req,res,req.params.id);if(!granted)return;res.json({product:"GameIndex",version:"0.92.0",run:safeRun(granted.run),items:listConstructionItems(granted.run.id),events:listConstructionEvents(granted.run.id,{limit:1000}),redacted:true});}));
}
