import { randomUUID } from "node:crypto";
import { db, schemaVersion, storageOrigin } from "../database/connection.mjs";
import { currentAuth } from "../auth/auth-service.mjs";
import { accessSnapshot, CAPABILITIES, requireCapability, requireSameOriginMutation } from "../access/capability-service.mjs";
import { creatorSummary, getCreatorUser, listRoleAudit, searchCreatorUsers, setManualPlan, setStaffRole, setStaffSuspension } from "../database/repositories/creator-control-repository.mjs";
import { createPublicBugReport, getPublicBugReportStatus, publicReportMetrics } from "../database/repositories/public-bug-report-repository.mjs";
import { approveContentManifest, contentCoverage, createContentManifest, ensureGameBlueprint, getContentManifest, getGameBlueprint, latestContentManifest, resolveGame, startUniverseBuild, syncUniverseBuild, universeGraph, updateGameBlueprint } from "../universe/universe-service.mjs";
import { createDraft, getCollection, getDraft, listCollections, listDrafts, previewDraft, publishDraft, compareDraft, restorePageVersion, saveCollection, saveDraft, validateDraft } from "../studio/creator-studio-service.mjs";
import { assignTester, createTestCampaign, createTestFeedback, createTesterInvitation, listCampaigns, listTestFeedback, saveChecklist, testerAssignments, updateTestFeedback } from "../tester/tester-service.mjs";
import { dexterStatus } from "../dexter/dexter-service.mjs";
import { core85Health } from "../core85/control-plane.mjs";
import { getImage3Asset, image3AssetDetail, imageEngine3Summary } from "../images/image-engine3.mjs";
import { getConstructionRun, requestConstructionCancel, requestConstructionPause, resetFailedConstructionItems, resumeConstructionRun } from "../database/repositories/construction-repository.mjs";
import { scheduleConstructionRun } from "../construction/construction-runner.mjs";
import { gameCount, listGames } from "../database/repositories/game-repository.mjs";
import { pageCount } from "../database/repositories/page-repository.mjs";

function requestId(req){return String(req.headers["x-request-id"]||randomUUID()).slice(0,120);}
function actor(req){return currentAuth(req)?.user?.id||null;}
function failure(res,error,status=400,req=null){const code=String(error?.code||"BETA095_REQUEST_FAILED").slice(0,120);return res.status(code.includes("CONFLICT")?409:status).json({ok:false,error:{requestId:req?requestId(req):randomUUID(),code,message:String(error?.message||"Não foi possível concluir a operação.").slice(0,600),component:"BETA095_API",retryable:false,...(error?.currentRevision?{currentRevision:error.currentRevision}:{})}});}
function gameFrom(req){return resolveGame(req.params.game||req.params.slug||req.body?.gameId||req.query.gameId);}
function originOf(req){const proto=String(req.headers["x-forwarded-proto"]||req.protocol||"https").split(",")[0],host=String(req.headers["x-forwarded-host"]||req.headers.host||"localhost").split(",")[0];return `${proto}://${host}`;}
function summaryCount(sql,args=[]){try{return Number(db.prepare(sql).get(...args)?.count||0);}catch{return 0;}}
function mutation(handler){return (req,res)=>{try{return handler(req,res);}catch(error){return failure(res,error,400,req);}};}
function asyncMutation(handler){return (req,res)=>Promise.resolve(handler(req,res)).catch(error=>failure(res,error,500,req));}

export function registerBeta095Routes(app,{publicBugLimiter,generationLimiter}={}){
  const publicLimit=publicBugLimiter||((req,res,next)=>next()),generationLimit=generationLimiter||((req,res,next)=>next());
  app.get("/api/beta095/status",(req,res)=>res.json({product:"GameIndex",version:"Beta 0.986",semanticVersion:"0.986.0",codename:"Production Consolidation",schema:schemaVersion(),games:gameCount(),pages:pageCount(),storageOrigin,intelligence:"GI_CORE_8.5_SCRIPTS + DEXTER_OLLAMA_OPTIONAL",imageRuntime:"IMAGE_ENGINE_3_NATIVE",architecture:"SCRIPT_RESEARCH_TO_VERIFY_TO_BUILD_TO_IMAGE3",mode:"LOCAL_FIRST_NO_API_KEY",apiKeyRequired:false,publicReports:publicReportMetrics(),workers:{construction:true,universeBuilder:"3.0"}}));
  app.get("/api/beta095/my-access",(req,res)=>res.json(accessSnapshot(req)));
  app.get("/api/beta095/capabilities",(req,res)=>res.json({available:CAPABILITIES,access:accessSnapshot(req),roles:["CREATOR","DEV","TESTER","NONE"],plans:["PRO","FREE"]}));

  app.use("/api/creator-control",requireSameOriginMutation);
  app.get("/api/creator-control/summary",requireCapability("creator_control"),mutation((req,res)=>res.json({ok:true,summary:creatorSummary()})));
  app.get("/api/creator-control/users",requireCapability("creator_control"),mutation((req,res)=>{const offset=Math.max(0,Number(req.query.cursor||req.query.offset)||0),result=searchCreatorUsers({q:req.query.q||"",role:req.query.role||"",plan:req.query.plan||"",status:req.query.status||"",sort:req.query.sort||"createdAt",direction:req.query.direction||"desc",limit:req.query.limit||30,offset});res.json({...result,nextCursor:offset+result.entries.length<result.total?String(offset+result.entries.length):null});}));
  app.get("/api/creator-control/users/:id",requireCapability("creator_control"),mutation((req,res)=>{const user=getCreatorUser(req.params.id);if(!user)return res.status(404).json({ok:false,error:{code:"USER_NOT_FOUND",message:"Usuário não encontrado."}});res.json({ok:true,user,audit:listRoleAudit({targetUserId:user.id,limit:30}).entries});}));
  const staffRoleMutation=mutation((req,res)=>res.json(setStaffRole({actorUserId:actor(req),targetUserId:req.params.id,nextRole:req.body?.role,expectedRole:req.body?.expectedRole,expectedRevision:req.body?.expectedRevision,reason:req.body?.reason,requestId:requestId(req)})));
  const staffSuspensionMutation=mutation((req,res)=>res.json(setStaffSuspension({actorUserId:actor(req),targetUserId:req.params.id,suspended:req.body?.suspended,expectedRevision:req.body?.expectedRevision,reason:req.body?.reason,requestId:requestId(req)})));
  const manualPlanMutation=mutation((req,res)=>res.json(setManualPlan({actorUserId:actor(req),targetUserId:req.params.id,active:req.body?.active,expiresAt:req.body?.expiresAt,expectedRevision:req.body?.expectedRevision,reason:req.body?.reason,requestId:requestId(req)})));
  app.post("/api/creator-control/users/:id/staff-role",requireCapability("manage_staff_roles"),staffRoleMutation);app.patch("/api/creator-control/users/:id/staff-role",requireCapability("manage_staff_roles"),staffRoleMutation);
  app.post("/api/creator-control/users/:id/staff-suspension",requireCapability("manage_staff_roles"),staffSuspensionMutation);app.patch("/api/creator-control/users/:id/status",requireCapability("manage_staff_roles"),staffSuspensionMutation);
  app.post("/api/creator-control/users/:id/manual-plan",requireCapability("manage_account_plans"),manualPlanMutation);app.patch("/api/creator-control/users/:id/plan",requireCapability("manage_account_plans"),manualPlanMutation);
  app.get("/api/creator-control/audit",requireCapability("view_role_audit"),mutation((req,res)=>res.json({ok:true,...listRoleAudit({limit:req.query.limit||80,offset:req.query.offset||0,targetUserId:req.query.targetUserId||null})})));
  app.post("/api/creator-control/tester-invitations",requireCapability("manage_staff_roles"),mutation((req,res)=>res.status(201).json({ok:true,invitation:createTesterInvitation({actorUserId:actor(req),...req.body})})));

  app.post("/api/public/bug-reports",publicLimit,requireSameOriginMutation,mutation((req,res)=>res.status(201).json(createPublicBugReport(req.body||{},{reporterUserId:actor(req),origin:originOf(req)}))));
  app.get("/api/public/bug-reports/:receipt/status",publicLimit,mutation((req,res)=>{const report=getPublicBugReportStatus(req.params.receipt,{reporterUserId:actor(req)});if(!report)return res.status(404).json({ok:false,error:{code:"REPORT_NOT_FOUND",message:"Comprovante não encontrado."}});res.json({ok:true,report});}));

  app.use("/api/universe",requireSameOriginMutation);
  app.get("/api/universe/games/:game/blueprint",requireCapability("universe_build"),mutation((req,res)=>{const game=gameFrom(req);if(!game)throw new Error("Jogo não encontrado.");res.json({ok:true,game:{id:game.id,slug:game.slug,name:game.nome},blueprint:getGameBlueprint(game.id)||ensureGameBlueprint(game.id,{userId:actor(req),language:req.query.language||"pt-BR"})});}));
  app.put("/api/universe/games/:game/blueprint",requireCapability("universe_build"),mutation((req,res)=>{const game=gameFrom(req);if(!game)throw new Error("Jogo não encontrado.");res.json({ok:true,blueprint:updateGameBlueprint(game.id,req.body||{},actor(req))});}));
  app.post("/api/universe/games/:game/manifests",generationLimit,requireCapability("universe_build"),mutation((req,res)=>{const game=gameFrom(req);if(!game)throw new Error("Jogo não encontrado.");res.status(201).json({ok:true,manifest:createContentManifest(game.id,{language:req.body?.language||"pt-BR",mode:req.body?.mode||"FULL",userId:actor(req)})});}));
  app.get("/api/universe/games/:game/manifests/latest",requireCapability("universe_build"),mutation((req,res)=>{const game=gameFrom(req);if(!game)throw new Error("Jogo não encontrado.");res.json({ok:true,manifest:latestContentManifest(game.id,req.query.language||"pt-BR")});}));
  app.get("/api/universe/manifests/:id",requireCapability("universe_build"),mutation((req,res)=>{const manifest=getContentManifest(req.params.id);if(!manifest)return res.status(404).json({ok:false,error:{code:"MANIFEST_NOT_FOUND",message:"Manifesto não encontrado."}});res.json({ok:true,manifest});}));
  app.post("/api/universe/manifests/:id/revalidate",generationLimit,requireCapability("universe_build"),mutation((req,res)=>{const current=getContentManifest(req.params.id);if(!current)throw new Error("Manifesto não encontrado.");res.json({ok:true,manifest:createContentManifest(current.gameId,{language:current.language,mode:current.mode,userId:actor(req)})});}));
  app.post("/api/universe/manifests/:id/approve",requireCapability("creator_control"),mutation((req,res)=>res.json({ok:true,manifest:approveContentManifest(req.params.id,actor(req))})));
  app.get("/api/universe/games/:game/coverage",requireCapability("universe_build"),mutation((req,res)=>{const game=gameFrom(req);if(!game)throw new Error("Jogo não encontrado.");res.json({ok:true,coverage:contentCoverage(game.id,{language:req.query.language||"pt-BR"})});}));
  app.get("/api/universe/games/:game/graph",requireCapability("universe_build"),mutation((req,res)=>{const game=gameFrom(req);if(!game)throw new Error("Jogo não encontrado.");res.json({ok:true,graph:universeGraph(game.id,{language:req.query.language||"pt-BR",limit:req.query.limit||300})});}));
  app.post("/api/universe/manifests/:id/build",generationLimit,requireCapability("universe_build"),mutation((req,res)=>res.status(202).json({ok:true,...startUniverseBuild(req.params.id,{userId:actor(req),includeImages:req.body?.includeImages===true,mode:req.body?.mode||"FULL",requestId:requestId(req)})})));
  app.get("/api/universe/build-runs/:id",requireCapability("universe_build"),mutation((req,res)=>{const run=syncUniverseBuild(req.params.id);if(!run)return res.status(404).json({ok:false,error:{code:"UNIVERSE_RUN_NOT_FOUND",message:"Construção não encontrada."}});res.json({ok:true,universeRun:run});}));
  for(const [action,handler] of [["pause",requestConstructionPause],["cancel",requestConstructionCancel]])app.post(`/api/universe/build-runs/:id/${action}`,requireCapability("universe_build"),mutation((req,res)=>{const universe=syncUniverseBuild(req.params.id);if(!universe)throw new Error("Construção não encontrada.");res.json({ok:true,run:handler(universe.constructionRunId),universeRun:syncUniverseBuild(req.params.id)});}));
  app.post("/api/universe/build-runs/:id/resume",requireCapability("universe_build"),mutation((req,res)=>{const universe=syncUniverseBuild(req.params.id);if(!universe)throw new Error("Construção não encontrada.");const run=resumeConstructionRun(universe.constructionRunId);scheduleConstructionRun(run.id);res.status(202).json({ok:true,run,universeRun:syncUniverseBuild(req.params.id)});}));
  app.post("/api/universe/build-runs/:id/retry-failed",requireCapability("universe_build"),mutation((req,res)=>{const universe=syncUniverseBuild(req.params.id);if(!universe)throw new Error("Construção não encontrada.");const run=resetFailedConstructionItems(universe.constructionRunId);scheduleConstructionRun(run.id);res.status(202).json({ok:true,run,universeRun:syncUniverseBuild(req.params.id)});}));

  app.use("/api/creator-studio",requireSameOriginMutation);
  app.get("/api/creator-studio/drafts",requireCapability("creator_studio_edit"),mutation((req,res)=>res.json({ok:true,entries:listDrafts({gameId:req.query.gameId||null,status:req.query.status||null,limit:req.query.limit||80})})));
  app.post("/api/creator-studio/drafts",requireCapability("creator_studio_edit"),mutation((req,res)=>res.status(201).json({ok:true,draft:createDraft({...req.body,ownerUserId:actor(req)})})));
  app.get("/api/creator-studio/drafts/:id",requireCapability("creator_studio_edit"),mutation((req,res)=>{const draft=getDraft(req.params.id);if(!draft)return res.status(404).json({ok:false,error:{code:"DRAFT_NOT_FOUND",message:"Rascunho não encontrado."}});res.json({ok:true,draft});}));
  app.put("/api/creator-studio/drafts/:id",requireCapability("creator_studio_edit"),mutation((req,res)=>res.json({ok:true,...saveDraft(req.params.id,req.body||{},actor(req))})));
  app.post("/api/creator-studio/drafts/:id/autosave",requireCapability("creator_studio_edit"),mutation((req,res)=>res.json({ok:true,...saveDraft(req.params.id,req.body||{},actor(req))})));
  app.get("/api/creator-studio/drafts/:id/preview",requireCapability("creator_studio_edit"),mutation((req,res)=>res.json({ok:true,preview:previewDraft(req.params.id)})));
  app.post("/api/creator-studio/drafts/:id/validate",requireCapability("creator_studio_edit"),mutation((req,res)=>res.json({ok:true,...validateDraft(req.params.id)})));
  app.get("/api/creator-studio/drafts/:id/compare",requireCapability("creator_studio_edit"),mutation((req,res)=>res.json({ok:true,...compareDraft(req.params.id)})));
  app.post("/api/creator-studio/drafts/:id/publish",requireCapability("content_publish"),mutation((req,res)=>res.json({ok:true,...publishDraft(req.params.id,actor(req))})));
  app.post("/api/creator-studio/pages/:pageId/versions/:versionId/restore",requireCapability("content_publish"),mutation((req,res)=>res.json({ok:true,...restorePageVersion(req.params.pageId,req.params.versionId,actor(req))})));
  app.get("/api/creator-studio/collections",requireCapability("creator_studio_edit"),mutation((req,res)=>res.json({ok:true,entries:listCollections(req.query.gameId)})));
  app.post("/api/creator-studio/collections",requireCapability("creator_studio_edit"),mutation((req,res)=>res.status(201).json({ok:true,collection:saveCollection(req.body||{},actor(req))})));
  app.put("/api/creator-studio/collections/:id",requireCapability("creator_studio_edit"),mutation((req,res)=>res.json({ok:true,collection:saveCollection({...req.body,id:req.params.id},actor(req))})));
  app.get("/api/creator-studio/collections/:id",requireCapability("creator_studio_edit"),mutation((req,res)=>{const collection=getCollection(req.params.id);if(!collection)return res.status(404).json({ok:false,error:{code:"COLLECTION_NOT_FOUND",message:"Coleção não encontrada."}});res.json({ok:true,collection});}));

  app.use("/api/tester-lab",requireSameOriginMutation);
  app.get("/api/tester-lab/assignments",requireCapability("tester_preview"),mutation((req,res)=>res.json({ok:true,entries:testerAssignments(actor(req))})));
  app.post("/api/tester-lab/assignments/:campaignId/checklist",requireCapability("tester_feedback"),mutation((req,res)=>res.json({ok:true,result:saveChecklist(req.params.campaignId,actor(req),req.body?.results||{})})));
  app.post("/api/tester-lab/feedback",requireCapability("tester_feedback"),mutation((req,res)=>res.status(201).json({ok:true,feedback:createTestFeedback(req.body||{},actor(req))})));
  app.get("/api/tester-lab/my-feedback",requireCapability("tester_feedback"),mutation((req,res)=>res.json({ok:true,entries:listTestFeedback({testerUserId:actor(req),limit:req.query.limit||100})})));
  app.get("/api/tester-lab/campaigns",requireCapability("bug_triage"),mutation((req,res)=>res.json({ok:true,entries:listCampaigns({limit:req.query.limit||100})})));
  app.post("/api/tester-lab/campaigns",requireCapability("bug_triage"),mutation((req,res)=>res.status(201).json({ok:true,campaign:createTestCampaign(req.body||{},actor(req))})));
  app.post("/api/tester-lab/campaigns/:id/assign",requireCapability("manage_staff_roles"),mutation((req,res)=>res.json({ok:true,assignment:assignTester(req.params.id,req.body?.testerUserId,actor(req))})));
  app.get("/api/tester-lab/feedback",requireCapability("bug_triage"),mutation((req,res)=>res.json({ok:true,entries:listTestFeedback({campaignId:req.query.campaignId||null,status:req.query.status||null,limit:req.query.limit||100})})));
  app.patch("/api/tester-lab/feedback/:id",requireCapability("bug_triage"),mutation((req,res)=>res.json({ok:true,feedback:updateTestFeedback(req.params.id,req.body||{})})));

  app.use("/api/image-library",requireSameOriginMutation);
  app.get("/api/image-library/games/:game",requireCapability("image_management"),mutation((req,res)=>{const game=gameFrom(req);if(!game)throw new Error("Jogo não encontrado.");const ids=db.prepare(`SELECT id FROM ie3_assets WHERE game_id=? ORDER BY updated_at DESC LIMIT ?`).all(game.id,Math.min(200,Number(req.query.limit)||120));res.json({ok:true,engine:"IMAGE_ENGINE_3",game:{id:game.id,slug:game.slug,name:game.nome},assets:ids.map(x=>getImage3Asset(x.id)).filter(Boolean)});}));
  app.all("/api/image-library/games/:game/manual",requireCapability("image_management"),mutation((req,res)=>res.status(410).json({ok:false,error:{code:"LEGACY_IMAGE_WORKFLOW_REMOVED",message:"O fluxo manual antigo foi removido. Image Engine 3 faz descoberta, validação, persistência e reparo automaticamente."}})));
  app.post("/api/image-library/assets/:id/transform",requireCapability("image_management"),mutation((req,res)=>res.status(410).json({ok:false,error:{code:"LEGACY_IMAGE_TRANSFORM_REMOVED",message:"Transformações do Asset Library antigo não fazem parte do runtime HF2."}})));
  app.get("/api/image-library/assets/:id/history",requireCapability("image_management"),mutation((req,res)=>{const asset=image3AssetDetail(req.params.id,{candidateLimit:60,attemptLimit:120});if(!asset)return res.status(404).json({ok:false,error:{code:"ASSET_NOT_FOUND"}});res.json({ok:true,engine:"IMAGE_ENGINE_3",asset});}));

  app.get("/api/ai6/status",requireCapability("ai_diagnostics"),asyncMutation(async(req,res)=>res.json({ok:true,deprecated:true,replacedBy:"GI_CORE_8.5 + DEXTER",core:await core85Health({probeDexter:false}),dexter:await dexterStatus({probe:false})})));
  app.post("/api/ai6/evaluations",generationLimit,requireCapability("ai_diagnostics"),mutation((req,res)=>res.status(410).json({ok:false,error:{code:"AI6_REMOVED",message:"AI System 6 foi removido do runtime. Use os diagnósticos do GI Core 8.5 e Dexter."}})));

  app.get("/api/showcase",(req,res)=>{const games=listGames({includeDrafts:false}).filter(g=>String(g.entityType||"GAME").toUpperCase()==="GAME").slice(0,6),metrics={games:gameCount(),pages:pageCount(),publishedPages:summaryCount(`SELECT COUNT(*) count FROM pages WHERE status='PUBLISHED'`),universeManifests:summaryCount(`SELECT COUNT(*) count FROM content_manifests`),completedBuilds:summaryCount(`SELECT COUNT(*) count FROM construction_runs WHERE status='COMPLETED'`),safeImages:imageEngine3Summary().ready};res.json({product:"GameIndex",version:"Beta 0.95",intelligence:"GI Core 8.5 + Dexter optional",visualPolicy:"NO_PEOPLE_NO_WOMEN",metrics,games:games.map(game=>({id:game.id,slug:game.slug,name:game.nome,description:game.descricao})),realStateOnly:true});});

  app.get("/api/beta095/diagnostics",requireCapability("deployment_monitor"),mutation((req,res)=>{const required=["staff_role_assignments","role_change_audit","public_bug_reports","game_blueprints","content_manifests","creator_drafts","ai6_handoffs"],tables=Object.fromEntries(required.map(name=>[name,Boolean(db.prepare(`SELECT 1 FROM sqlite_master WHERE type='table' AND name=?`).get(name))]));res.json({ok:true,version:"0.95.0",schema:schemaVersion(),storageOrigin,tables,creatorAssignments:summaryCount(`SELECT COUNT(*) count FROM staff_role_assignments WHERE role='CREATOR'`),orphanManifests:summaryCount(`SELECT COUNT(*) count FROM content_manifests m LEFT JOIN games g ON g.id=m.game_id WHERE g.id IS NULL`),orphanDrafts:summaryCount(`SELECT COUNT(*) count FROM creator_drafts d LEFT JOIN games g ON g.id=d.game_id WHERE g.id IS NULL`),publicReportQueue:publicReportMetrics(),intelligence:"GI_CORE_8.5_SCRIPTS",images:imageEngine3Summary(),secretsRedacted:true});}));
}
