import { createHash, randomUUID } from "node:crypto";
import { db, json, nowIso, parseJson, transaction } from "../database/connection.mjs";
import { getGameById, getGameBySlug } from "../database/repositories/game-repository.mjs";
import { createConstructionRun, getConstructionRun, listConstructionItems } from "../database/repositories/construction-repository.mjs";
import { scheduleConstructionRun } from "../construction/construction-runner.mjs";
import { evaluateKnowledgeQuality } from "../autonomy/knowledge-quality-gate.mjs";
import { slugify, stableId } from "../knowledge/normalize.mjs";

export const WAVES=Object.freeze(["FOUNDATION","UNIVERSE","ITEMS","GUIDES","CONNECTIONS","IMAGES_AND_REVIEW"]);
const BLUEPRINT_CATEGORIES=[
  ["overview","Overview",true,"GAME"],["history","History and lore",true,"TIMELINE"],["mechanics","Mechanics",true,"GAME"],["modes","Game modes",true,"GAME"],
  ["characters","Characters",false,"ENTITY"],["enemies","Enemies and mobs",false,"BOSS"],["bosses","Bosses",false,"BOSS"],["weapons","Weapons",false,"ITEM"],
  ["tools","Tools",false,"ITEM"],["items","Items and resources",false,"ITEM"],["locations","Locations and maps",false,"LOCATION"],["biomes","Biomes and worlds",false,"LOCATION"],
  ["structures","Structures",false,"LOCATION"],["vehicles","Vehicles",false,"ITEM"],["factions","Factions",false,"ENTITY"],["progression","Progression",true,"GUIDE"],
  ["beginner-guides","Beginner guides",true,"GUIDE"],["advanced-guides","Advanced guides",false,"GUIDE"],["faq","Frequently asked questions",true,"GUIDE"],["glossary","Glossary",true,"GUIDE"],
  ["updates","Timeline and updates",true,"TIMELINE"],["related","Related game and franchise",true,"GAME"]
];
const RECIPES={
  GAME:["identity","facts","premise","gameplay","categories","universe","beginner-path","updates","sources"],
  ENTITY:["identity","context","abilities","appearances","relationships","relevance","related-guides","sources"],
  BOSS:["overview","location","behavior","attacks","phases","strategy","rewards","related","sources"],
  ITEM:["overview","acquisition","attributes","usage","strengths-limitations","upgrades","comparisons","related-guides","sources"],
  LOCATION:["overview","access","environment","points-of-interest","resources","enemies-events","strategies","related","sources"],
  GUIDE:["objective","prerequisites","steps","warnings","alternatives","expected-result","related","sources"],
  TIMELINE:["date-version","verified-summary","affected-content","sources","stale-impact"]
};
const TYPE_CATEGORY={BOSS:"bosses",ENEMY:"enemies",MOB:"enemies",WEAPON:"weapons",TOOL:"tools",ITEM:"items",RESOURCE:"items",MATERIAL:"items",LOCATION:"locations",MAP:"locations",BIOME:"biomes",DIMENSION:"biomes",WORLD:"biomes",STRUCTURE:"structures",VEHICLE:"vehicles",FACTION:"factions",CHARACTER:"characters",NPC:"characters",MECHANIC:"mechanics",MODE:"modes",UPDATE:"updates",GUIDE:"advanced-guides"};

function recipeForType(type=""){const t=String(type).toUpperCase();if(["BOSS","ENEMY","MOB"].includes(t))return "BOSS";if(["WEAPON","TOOL","ITEM","RESOURCE","MATERIAL","VEHICLE","EQUIPMENT","COLLECTIBLE"].includes(t))return "ITEM";if(["LOCATION","MAP","BIOME","DIMENSION","WORLD","STRUCTURE"].includes(t))return "LOCATION";if(["GUIDE","STRATEGY","BUILD","FAQ","GLOSSARY"].includes(t))return "GUIDE";if(["UPDATE","TIMELINE","HISTORY"].includes(t))return "TIMELINE";return "ENTITY";}
function waveFor(recipe){if(recipe==="GAME"||recipe==="TIMELINE")return "FOUNDATION";if(recipe==="ENTITY"||recipe==="BOSS"||recipe==="LOCATION")return "UNIVERSE";if(recipe==="ITEM")return "ITEMS";if(recipe==="GUIDE")return "GUIDES";return "CONNECTIONS";}
function mapBlueprint(row){if(!row)return null;return {id:row.id,gameId:row.game_id,language:row.language,version:Number(row.version),status:row.status,createdBy:row.created_by,createdAt:row.created_at,updatedAt:row.updated_at,categories:db.prepare(`SELECT * FROM game_blueprint_categories WHERE blueprint_id=? ORDER BY position,label`).all(row.id).map(c=>({id:c.id,key:c.category_key,label:c.label,enabled:Boolean(c.enabled),position:Number(c.position),recipeKey:c.recipe_key,configuration:parseJson(c.configuration_json,{})}))};}
function mapManifest(row,{withItems=true}={}){if(!row)return null;const result={id:row.id,gameId:row.game_id,blueprintId:row.blueprint_id,language:row.language,version:Number(row.version),mode:row.mode,status:row.status,summary:parseJson(row.summary_json,{}),approvedBy:row.approved_by,createdBy:row.created_by,createdAt:row.created_at,updatedAt:row.updated_at,approvedAt:row.approved_at};if(withItems)result.items=db.prepare(`SELECT * FROM content_manifest_items WHERE manifest_id=? ORDER BY CASE wave WHEN 'FOUNDATION' THEN 1 WHEN 'UNIVERSE' THEN 2 WHEN 'ITEMS' THEN 3 WHEN 'GUIDES' THEN 4 WHEN 'CONNECTIONS' THEN 5 ELSE 6 END,title`).all(row.id).map(mapManifestItem);return result;}
function mapManifestItem(r){return {id:r.id,manifestId:r.manifest_id,gameId:r.game_id,entityId:r.entity_id,categoryKey:r.category_key,pageType:r.page_type,recipeKey:r.recipe_key,wave:r.wave,title:r.title,slug:r.slug_candidate,language:r.language,requiredSections:parseJson(r.required_sections_json,[]),imageRoles:parseJson(r.image_roles_json,[]),knowledgeCoverage:Number(r.knowledge_coverage),sourceCoverage:Number(r.source_coverage),qualityReadiness:Number(r.quality_readiness),status:r.status,reason:r.reason,suggestedAction:r.suggested_action,resultPageId:r.result_page_id,createdAt:r.created_at,updatedAt:r.updated_at};}
function sourceCount(entityId){return Number(db.prepare(`SELECT COUNT(*) count FROM claims c JOIN knowledge k ON k.id=c.knowledge_id WHERE k.entity_id=? AND c.source_ids_json<>'[]'`).get(entityId)?.count||0);}
function knowledgeStats(entityId){const row=db.prepare(`SELECT COUNT(*) count,COALESCE(AVG(confidence),0) confidence FROM knowledge WHERE entity_id=? AND status IN ('CURRENT','VALIDATED')`).get(entityId);return {count:Number(row?.count||0),confidence:Number(row?.confidence||0),sources:sourceCount(entityId)};}
function existingPage(gameId,entityId,pageType,language,slug){return entityId?db.prepare(`SELECT id,status,updated_at FROM pages WHERE game_id=? AND entity_id=? AND page_type=? AND language=? LIMIT 1`).get(gameId,entityId,pageType,language):db.prepare(`SELECT id,status,updated_at FROM pages WHERE game_id=? AND slug=? AND language=? LIMIT 1`).get(gameId,slug,language);}
function manifestSummary(items){const statuses={};for(const item of items)statuses[item.status]=(statuses[item.status]||0)+1;return {identified:items.length,ready:statuses.READY_TO_BUILD||0,needsResearch:statuses.NEEDS_RESEARCH||0,needsReview:statuses.NEEDS_REVIEW||0,blockedDependencies:statuses.BLOCKED_DEPENDENCY||0,exists:statuses.EXISTS||0,excluded:statuses.EXCLUDED||0,byWave:Object.fromEntries(WAVES.map(w=>[w,items.filter(x=>x.wave===w).length]))};}

export function ensurePageRecipes(){
  const now=nowIso();
  transaction(()=>{
    for(const [recipeKey,sections] of Object.entries(RECIPES)){
      const id=stableId("page-recipe-095",recipeKey);
      db.prepare(`INSERT INTO page_recipes(id,recipe_key,label,page_type,description,enabled,version,created_at,updated_at) VALUES(?,?,?,?,?,1,1,?,?) ON CONFLICT(recipe_key) DO UPDATE SET label=excluded.label,description=excluded.description,updated_at=excluded.updated_at`).run(id,recipeKey,`${recipeKey} detailed recipe`,recipeKey,"Evidence-grounded Beta 0.96 page recipe.",now,now);
      sections.forEach((section,index)=>{
        const blockType=section==="steps"?"STEPS":section==="sources"?"SOURCES":"PARAGRAPH";
        db.prepare(`INSERT INTO page_recipe_sections(id,recipe_id,section_key,label,block_type,required,position,validation_json) VALUES(?,?,?,?,?,1,?,?) ON CONFLICT(recipe_id,section_key) DO UPDATE SET label=excluded.label,position=excluded.position`).run(stableId("recipe-section-095",recipeKey,section),id,section,section.replaceAll("-"," "),blockType,index,json({minimumCharacters:section==="sources"?0:40,noFiller:true}));
      });
    }
  });
  return Object.keys(RECIPES);
}

export function ensureGameBlueprint(gameId,{language="pt-BR",userId=null}={}){const game=getGameById(gameId);if(!game)throw new Error("Jogo não encontrado.");ensurePageRecipes();let row=db.prepare(`SELECT * FROM game_blueprints WHERE game_id=?`).get(gameId);if(row)return mapBlueprint(row);const id=stableId("blueprint-095",gameId),now=nowIso(),types=new Set(db.prepare(`SELECT upper(type) type FROM entities WHERE game_id=?`).all(gameId).map(x=>x.type));transaction(()=>{db.prepare(`INSERT INTO game_blueprints(id,game_id,language,version,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).run(id,gameId,language,1,"DRAFT",userId,now,now);BLUEPRINT_CATEGORIES.forEach(([key,label,base,recipe],position)=>{const applicable=base||[...types].some(type=>(TYPE_CATEGORY[type]||"entities")===key);db.prepare(`INSERT INTO game_blueprint_categories(id,blueprint_id,category_key,label,enabled,position,recipe_key,configuration_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(stableId("blueprint-category-095",id,key),id,key,label,applicable?1:0,position,recipe,json({autoDetected:!base,visualPolicy:"NO_PEOPLE_NO_WOMEN"}),now,now);});});return mapBlueprint(db.prepare(`SELECT * FROM game_blueprints WHERE id=?`).get(id));}

export function getGameBlueprint(gameId){const row=db.prepare(`SELECT * FROM game_blueprints WHERE game_id=?`).get(gameId);return row?mapBlueprint(row):null;}
export function updateGameBlueprint(gameId,{categories=[],status=null},userId=null){let blueprint=ensureGameBlueprint(gameId,{userId});const allowedStatus=new Set(["DRAFT","VALIDATED","ACTIVE"]),now=nowIso();transaction(()=>{for(const input of categories){const key=String(input.key||"").trim().toLowerCase().replace(/[^a-z0-9-]/g,"-").slice(0,60);if(!key)continue;const existing=db.prepare(`SELECT * FROM game_blueprint_categories WHERE blueprint_id=? AND category_key=?`).get(blueprint.id,key),position=Math.max(0,Number(input.position??existing?.position??999));db.prepare(`INSERT INTO game_blueprint_categories(id,blueprint_id,category_key,label,enabled,position,recipe_key,configuration_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(blueprint_id,category_key) DO UPDATE SET label=excluded.label,enabled=excluded.enabled,position=excluded.position,recipe_key=excluded.recipe_key,configuration_json=excluded.configuration_json,updated_at=excluded.updated_at`).run(existing?.id||stableId("blueprint-category-095",blueprint.id,key),blueprint.id,key,String(input.label||existing?.label||key).slice(0,100),input.enabled===false?0:1,position,RECIPES[input.recipeKey]?input.recipeKey:existing?.recipe_key||"ENTITY",json(input.configuration||parseJson(existing?.configuration_json,{})),existing?.created_at||now,now);}db.prepare(`UPDATE game_blueprints SET version=version+1,status=?,updated_at=? WHERE id=?`).run(allowedStatus.has(status)?status:blueprint.status,now,blueprint.id);});return getGameBlueprint(gameId);}

export function createContentManifest(gameId,{language="pt-BR",mode="FULL",userId=null}={}){
  const game=getGameById(gameId);if(!game)throw new Error("Jogo não encontrado.");const blueprint=ensureGameBlueprint(gameId,{language,userId}),enabled=new Map(blueprint.categories.filter(c=>c.enabled).map(c=>[c.key,c])),entities=db.prepare(`SELECT * FROM entities WHERE game_id=? ORDER BY name`).all(gameId),facts=db.prepare(`SELECT COUNT(*) knowledge,COALESCE(MAX(updated_at),'') updated FROM knowledge WHERE game_id=?`).get(gameId),pages=db.prepare(`SELECT COUNT(*) pages,COALESCE(MAX(updated_at),'') updated FROM pages WHERE game_id=? AND language=?`).get(gameId,language),fingerprint=createHash("sha256").update(json({gameId,language,mode,blueprintVersion:blueprint.version,entities:entities.map(e=>[e.id,e.type,e.updated_at]),facts,pages})).digest("hex");
  const prior=db.prepare(`SELECT * FROM content_manifests WHERE game_id=? AND language=? AND mode=? ORDER BY version DESC LIMIT 1`).get(gameId,language,mode);if(prior&&parseJson(prior.summary_json,{}).fingerprint===fingerprint)return {...mapManifest(prior),reused:true};
  const version=Number(prior?.version||0)+1,id=randomUUID(),now=nowIso(),items=[];
  const hubSlug=game.slug,hubExisting=existingPage(game.id,null,"GAME",language,hubSlug);items.push({id:stableId("manifest-item-095",id,"GAME",hubSlug),gameId:game.id,entityId:null,categoryKey:"overview",pageType:"GAME",recipeKey:"GAME",wave:"FOUNDATION",title:game.nome,slug:hubSlug,requiredSections:RECIPES.GAME,imageRoles:["COVER","LOGO","BANNER"],knowledgeCoverage:1,sourceCoverage:1,qualityReadiness:1,status:hubExisting&&hubExisting.status!=="OUTDATED"?(mode==="EXPANSION"?"EXCLUDED":"EXISTS"):"READY_TO_BUILD",reason:hubExisting?"Current game hub already exists.":"Game identity and curated memory are available.",suggestedAction:hubExisting?"Keep the current page linked.":"Build the foundation page.",resultPageId:hubExisting?.id||null});
  for(const entity of entities){const recipe=recipeForType(entity.type),category=TYPE_CATEGORY[String(entity.type).toUpperCase()]||"entities";if(category!=="entities"&&!enabled.has(category))continue;const pageType=String(entity.type||recipe).toUpperCase(),stats=knowledgeStats(entity.id),quality=(()=>{try{return evaluateKnowledgeQuality({entityId:entity.id,pageType});}catch{return {passed:false,reasons:["QUALITY_CHECK_FAILED"]};}})(),existing=existingPage(game.id,entity.id,pageType,language,entity.slug);let status,reason,action;if(existing&&existing.status!=="OUTDATED"&&existing.status!=="FAILED"){status=mode==="EXPANSION"?"EXCLUDED":"EXISTS";reason="A current page already exists.";action="Keep the current page without duplication.";}else if(quality.passed){status="READY_TO_BUILD";reason="Planner and Page Builder readiness contract passed.";action="Build in the scheduled wave.";}else if(stats.count<2||stats.sources===0){status="NEEDS_RESEARCH";reason=`Knowledge/source coverage is insufficient (${stats.count} records, ${stats.sources} sourced claims).`;action="Research and revalidate before construction.";}else{status="NEEDS_REVIEW";reason=(quality.reasons||["Quality gate requires review."]).join(", ").slice(0,400);action="Review evidence and recipe coverage.";}
    items.push({id:stableId("manifest-item-095",id,entity.id,pageType),gameId:game.id,entityId:entity.id,categoryKey:category,pageType,recipeKey:recipe,wave:waveFor(recipe),title:entity.name,slug:entity.slug,requiredSections:RECIPES[recipe],imageRoles:recipe==="LOCATION"?["MAP","ENVIRONMENT"]:recipe==="ITEM"?["ITEM","ICON"]:["ABSTRACT","ICON"],knowledgeCoverage:Math.min(1,stats.count/3),sourceCoverage:Math.min(1,stats.sources/2),qualityReadiness:quality.passed?1:Math.min(.95,(stats.confidence+Math.min(1,stats.count/3)+Math.min(1,stats.sources/2))/3),status,reason,suggestedAction:action,resultPageId:existing?.id||null});}
  const summary={...manifestSummary(items),fingerprint,plannerContract:"BETA_092_QUALITY_GATE_SHARED",generatedAt:now};
  transaction(()=>{db.prepare(`INSERT INTO content_manifests(id,game_id,blueprint_id,language,version,mode,status,summary_json,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(id,game.id,blueprint.id,language,version,mode,"VERIFIED",json(summary),userId,now,now);const insert=db.prepare(`INSERT INTO content_manifest_items(id,manifest_id,game_id,entity_id,category_key,page_type,recipe_key,wave,title,slug_candidate,language,required_sections_json,image_roles_json,knowledge_coverage,source_coverage,quality_readiness,status,reason,suggested_action,result_page_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);items.forEach(item=>insert.run(item.id,id,item.gameId,item.entityId,item.categoryKey,item.pageType,item.recipeKey,item.wave,item.title,item.slug,language,json(item.requiredSections),json(item.imageRoles),item.knowledgeCoverage,item.sourceCoverage,item.qualityReadiness,item.status,item.reason,item.suggestedAction,item.resultPageId,now,now));const hub=items[0];for(const item of items.slice(1))db.prepare(`INSERT OR IGNORE INTO content_manifest_dependencies(manifest_item_id,depends_on_item_id,dependency_type,required) VALUES(?,?,?,1)`).run(item.id,hub.id,"GAME_HUB");});
  return mapManifest(db.prepare(`SELECT * FROM content_manifests WHERE id=?`).get(id));
}

export function getContentManifest(id){return mapManifest(db.prepare(`SELECT * FROM content_manifests WHERE id=?`).get(id));}
export function latestContentManifest(gameId,language="pt-BR"){return mapManifest(db.prepare(`SELECT * FROM content_manifests WHERE game_id=? AND language=? ORDER BY version DESC LIMIT 1`).get(gameId,language));}
export function approveContentManifest(id,userId){const row=db.prepare(`SELECT * FROM content_manifests WHERE id=?`).get(id);if(!row)throw new Error("Manifesto não encontrado.");const ready=Number(db.prepare(`SELECT COUNT(*) count FROM content_manifest_items WHERE manifest_id=? AND status='READY_TO_BUILD'`).get(id)?.count||0);if(!ready)throw new Error("O manifesto não possui itens prontos para construir.");db.prepare(`UPDATE content_manifests SET status='APPROVED',approved_by=?,approved_at=?,updated_at=? WHERE id=?`).run(userId,nowIso(),nowIso(),id);return getContentManifest(id);}

export function contentCoverage(gameId,{language="pt-BR"}={}){const discovered=Number(db.prepare(`SELECT COUNT(*) count FROM entities WHERE game_id=?`).get(gameId)?.count||0),manifest=latestContentManifest(gameId,language);if(!manifest)return {gameId,language,manifest:null,discovered,overallReadiness:0,planned:0,completed:0,researching:0,waitingKnowledge:0,readyToBuild:0,building:0,built:0,categories:[],gaps:{research:0,review:0,sources:0,images:0,dependencies:0,stale:0}};const active=manifest.items.filter(x=>x.status!=="EXCLUDED"),byCategory=new Map();for(const item of active){if(!byCategory.has(item.categoryKey))byCategory.set(item.categoryKey,[]);byCategory.get(item.categoryKey).push(item);}const categories=[...byCategory].map(([key,items])=>{const completed=items.filter(x=>["EXISTS","COMPLETED"].includes(x.status)||x.resultPageId).length,published=items.filter(x=>x.resultPageId&&db.prepare(`SELECT status FROM pages WHERE id=?`).get(x.resultPageId)?.status==="PUBLISHED").length;return {key,planned:items.length,completed,published,percentage:items.length?Math.round(completed/items.length*100):0,researchGaps:items.filter(x=>x.status==="NEEDS_RESEARCH").length,reviewGaps:items.filter(x=>x.status==="NEEDS_REVIEW").length};});const completed=active.filter(x=>["EXISTS","COMPLETED"].includes(x.status)||x.resultPageId).length,imagesMissing=active.filter(x=>x.resultPageId&&db.prepare(`SELECT COALESCE(image_ids_json,'[]') ids FROM pages WHERE id=?`).get(x.resultPageId)?.ids==="[]").length;return {gameId,language,manifest:{id:manifest.id,version:manifest.version,status:manifest.status},discovered,overallReadiness:active.length?Math.round(completed/active.length*100):0,planned:active.length,completed,researching:active.filter(x=>x.status==="RESEARCHING").length,waitingKnowledge:active.filter(x=>x.status==="NEEDS_RESEARCH").length,readyToBuild:active.filter(x=>x.status==="READY_TO_BUILD").length,building:active.filter(x=>x.status==="BUILDING").length,built:completed,categories,gaps:{research:active.filter(x=>x.status==="NEEDS_RESEARCH").length,review:active.filter(x=>x.status==="NEEDS_REVIEW").length,sources:active.filter(x=>x.sourceCoverage<.5).length,images:imagesMissing,dependencies:active.filter(x=>x.status==="BLOCKED_DEPENDENCY").length,stale:active.filter(x=>x.status==="OUTDATED").length}};}

export function universeEntityInventory(gameId,{language="pt-BR"}={}){
  const discovered=Number(db.prepare(`SELECT COUNT(*) count FROM entities WHERE game_id=?`).get(gameId)?.count||0);
  const classified=Number(db.prepare(`SELECT COUNT(*) count FROM entities WHERE game_id=? AND COALESCE(type,'')<>'' AND UPPER(type) NOT IN ('ENTITY','UNKNOWN')`).get(gameId)?.count||0);
  const withKnowledge=Number(db.prepare(`SELECT COUNT(DISTINCT e.id) count FROM entities e JOIN knowledge k ON k.entity_id=e.id WHERE e.game_id=? AND k.status IN ('CURRENT','VALIDATED','NEEDS_REVIEW')`).get(gameId)?.count||0);
  const withPage=Number(db.prepare(`SELECT COUNT(DISTINCT entity_id) count FROM pages WHERE game_id=? AND language=? AND entity_id IS NOT NULL`).get(gameId,language)?.count||0);
  const withImages=Number(db.prepare(`SELECT COUNT(DISTINCT entity_id) count FROM images WHERE game_id=? AND entity_id IS NOT NULL AND verified=1 AND status IN ('APPROVED','VALIDATED','CURRENT')`).get(gameId)?.count||0);
  const coverage=contentCoverage(gameId,{language});
  return {gameId,language,discoveredEntities:discovered,classifiedEntities:classified,unclassifiedEntities:Math.max(0,discovered-classified),entitiesWithKnowledge:withKnowledge,entitiesWithoutKnowledge:Math.max(0,discovered-withKnowledge),entitiesWithPage:withPage,entitiesWithoutPage:Math.max(0,discovered-withPage),entitiesWithImages:withImages,entitiesWithoutImages:Math.max(0,discovered-withImages),planning:{discovered:coverage.discovered,inManifest:coverage.planned,researchRequired:coverage.waitingKnowledge,ready:coverage.readyToBuild,building:coverage.building,built:coverage.built,reviewRequired:Number(coverage.gaps?.review||0),blocked:Number(coverage.gaps?.dependencies||0)},readiness:{overall:coverage.overallReadiness,knowledge:discovered?Math.round(withKnowledge/discovered*100):0,pages:discovered?Math.round(withPage/discovered*100):0,images:discovered?Math.round(withImages/discovered*100):0}};
}

export function universeGraph(gameId,{language="pt-BR",limit=300}={}){const game=getGameById(gameId);if(!game)throw new Error("Jogo não encontrado.");const entities=db.prepare(`SELECT id,name,slug,type FROM entities WHERE game_id=? ORDER BY name LIMIT ?`).all(gameId,Math.min(500,Number(limit)||300)),pages=db.prepare(`SELECT id,entity_id,title,slug,page_type,status FROM pages WHERE game_id=? AND language=? ORDER BY title LIMIT ?`).all(gameId,language,Math.min(500,Number(limit)||300)),relationships=db.prepare(`SELECT id,source_entity_id,target_entity_id,relation_type FROM relationships WHERE game_id=? LIMIT 1000`).all(gameId);const nodes=[{id:`game:${game.id}`,kind:"GAME",label:game.nome,status:"CURRENT",href:`/game.html?slug=${encodeURIComponent(game.slug)}`}];for(const entity of entities)nodes.push({id:`entity:${entity.id}`,kind:"ENTITY",type:entity.type,label:entity.name,status:"KNOWN",href:`/entity.html?id=${encodeURIComponent(entity.id)}`});for(const page of pages)nodes.push({id:`page:${page.id}`,kind:"PAGE",type:page.page_type,label:page.title,status:page.status,href:`/generated-page.html?id=${encodeURIComponent(page.id)}`});const edges=[];for(const entity of entities)edges.push({id:`owns:${entity.id}`,source:`game:${game.id}`,target:`entity:${entity.id}`,type:"CONTAINS"});for(const page of pages)edges.push({id:`page:${page.id}`,source:page.entity_id?`entity:${page.entity_id}`:`game:${game.id}`,target:`page:${page.id}`,type:"HAS_PAGE"});for(const rel of relationships)edges.push({id:`rel:${rel.id}`,source:`entity:${rel.source_entity_id}`,target:`entity:${rel.target_entity_id}`,type:rel.relation_type});const manifest=latestContentManifest(gameId,language),planning=new Map((manifest?.items||[]).filter(x=>x.entityId).map(x=>[x.entityId,x.status]));return {game:{id:game.id,slug:game.slug,name:game.nome},nodes,edges,list:entities.map(e=>({id:e.id,label:e.name,type:e.type,related:relationships.filter(r=>r.source_entity_id===e.id||r.target_entity_id===e.id).length,page:pages.find(p=>p.entity_id===e.id)||null,planningStatus:planning.get(e.id)||"DISCOVERED"})),clustered:nodes.length>120,truncated:entities.length>=limit};}

export function startUniverseBuild(manifestId,{userId,includeImages=false,mode="FULL",requestId=randomUUID()}={}){const manifest=getContentManifest(manifestId);if(!manifest)throw new Error("Manifesto não encontrado.");if(manifest.status!=="APPROVED")throw new Error("Aprove o Content Manifest antes de iniciar.");const ready=manifest.items.filter(x=>x.status==="READY_TO_BUILD").sort((a,b)=>WAVES.indexOf(a.wave)-WAVES.indexOf(b.wave)||a.title.localeCompare(b.title));if(!ready.length)throw new Error("Nenhum item está pronto para construir.");const plan=ready.map(item=>({entityId:item.entityId,pageType:item.pageType,maxAttempts:3})),run=createConstructionRun({requestId,userId,gameId:manifest.gameId,language:manifest.language,researchMode:"DEEP",publishMode:"PREVIEW_ONLY",includeImages,demoMode:mode==="DEMO",plan});if(run.reused){const link=db.prepare(`SELECT id FROM universe_build_runs WHERE construction_run_id=?`).get(run.id);if(link)return {run:getConstructionRun(run.id),universeRunId:link.id,reused:true};throw new Error("Já existe outra construção ativa para este jogo e idioma.");}const universeRunId=randomUUID(),now=nowIso(),constructionItems=listConstructionItems(run.id);transaction(()=>{db.prepare(`UPDATE construction_runs SET pipeline_version='0.96',plan_json=? WHERE id=?`).run(json(ready.map(item=>({manifestItemId:item.id,entityId:item.entityId,pageType:item.pageType,wave:item.wave,title:item.title}))),run.id);db.prepare(`INSERT INTO universe_build_runs(id,manifest_id,construction_run_id,mode,pipeline_version,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).run(universeRunId,manifest.id,run.id,mode,"0.96",userId,now,now);WAVES.forEach((wave,position)=>{const count=ready.filter(x=>x.wave===wave).length;db.prepare(`INSERT INTO universe_build_waves(id,universe_run_id,wave,position,status,total_items,updated_at) VALUES(?,?,?,?,?,?,?)`).run(stableId("universe-wave-096",universeRunId,wave),universeRunId,wave,position,count?"QUEUED":"SKIPPED",count,now);});constructionItems.forEach((item,index)=>db.prepare(`INSERT INTO universe_build_item_links(universe_run_id,construction_item_id,manifest_item_id,wave) VALUES(?,?,?,?)`).run(universeRunId,item.id,ready[index].id,ready[index].wave));db.prepare(`UPDATE content_manifests SET status='BUILDING',updated_at=? WHERE id=?`).run(now,manifest.id);});const workerEnabled=String(process.env.GAMEINDEX_CONSTRUCTION_ENABLED??process.env.GAMEINDEX_FULL_BUILD_ENABLED??"true").toLowerCase()!=="false";if(workerEnabled)scheduleConstructionRun(run.id);return {run:getConstructionRun(run.id),universeRunId,reused:false,workerScheduled:workerEnabled,statusUrl:`/api/universe/build-runs/${universeRunId}`};}

export function syncUniverseBuild(universeRunId){const link=db.prepare(`SELECT u.*,c.status construction_status FROM universe_build_runs u JOIN construction_runs c ON c.id=u.construction_run_id WHERE u.id=?`).get(universeRunId);if(!link)return null;const now=nowIso();transaction(()=>{const items=db.prepare(`SELECT l.manifest_item_id,l.wave,c.status,c.result_page_id,c.image_status FROM universe_build_item_links l JOIN construction_items c ON c.id=l.construction_item_id WHERE l.universe_run_id=?`).all(universeRunId);for(const item of items){const mapped=item.status==="COMPLETED"?"COMPLETED":item.status==="FAILED"?"FAILED":item.status==="BLOCKED"?"BLOCKED_DEPENDENCY":item.status;db.prepare(`UPDATE content_manifest_items SET status=?,result_page_id=COALESCE(?,result_page_id),updated_at=? WHERE id=?`).run(mapped,item.result_page_id,now,item.manifest_item_id);}for(const wave of WAVES){const rows=items.filter(x=>x.wave===wave),completed=rows.filter(x=>x.status==="COMPLETED").length,failed=rows.filter(x=>["FAILED","BLOCKED"].includes(x.status)).length,running=rows.some(x=>x.status==="RUNNING"),status=!rows.length?"SKIPPED":completed+failed===rows.length?(failed?"PARTIAL":"COMPLETED"):running?"RUNNING":"QUEUED";db.prepare(`UPDATE universe_build_waves SET status=?,completed_items=?,failed_items=?,started_at=CASE WHEN ?='RUNNING' AND started_at='' THEN ? ELSE started_at END,completed_at=CASE WHEN ? IN ('COMPLETED','PARTIAL') THEN ? ELSE completed_at END,updated_at=? WHERE universe_run_id=? AND wave=?`).run(status,completed,failed,status,now,status,now,now,universeRunId,wave);}if(["COMPLETED","PARTIAL_SUCCESS","FAILED","BLOCKED_SYSTEMIC","CANCELLED"].includes(link.construction_status))db.prepare(`UPDATE content_manifests SET status=?,updated_at=? WHERE id=?`).run(link.construction_status==="COMPLETED"?"COMPLETED":"APPROVED",now,link.manifest_id);db.prepare(`UPDATE universe_build_runs SET updated_at=? WHERE id=?`).run(now,universeRunId);});const waves=db.prepare(`SELECT wave,status,total_items,completed_items,failed_items,started_at,completed_at FROM universe_build_waves WHERE universe_run_id=? ORDER BY position`).all(universeRunId).map(w=>({wave:w.wave,status:w.status,totalItems:Number(w.total_items),completedItems:Number(w.completed_items),failedItems:Number(w.failed_items),startedAt:w.started_at,completedAt:w.completed_at}));return {id:universeRunId,manifestId:link.manifest_id,constructionRunId:link.construction_run_id,mode:link.mode,pipelineVersion:link.pipeline_version,run:getConstructionRun(link.construction_run_id),waves,updatedAt:nowIso()};}

export function resolveGame(value){return getGameById(value)||getGameBySlug(value);}
