import { nowIso } from "../database/connection.mjs";
import { evaluateBuilderValidationI4 } from "./validation-099i4.mjs";
import { researchQualitySummary } from "../research/research-quality-099i5.mjs";
import { latestPreviewSnapshotI5, productionPipelineStateI5, setBuilderStage } from "./universe-production-pipeline-099i5.mjs";

function issue(code,message,severity="BLOCKER",details={}){return {code,message,severity,details};}
function uniq(rows=[]){const seen=new Set();return rows.filter(x=>{const k=`${x.code}|${x.message}`;if(seen.has(k))return false;seen.add(k);return true;});}

export function evaluateBuilderValidationI5(entityGameId,{revisionId=null,language="pt-BR",structureStatus=null,persist=true,buildId=null}={}){
  const base=evaluateBuilderValidationI4(entityGameId,{revisionId,language,structureStatus,persist:false}),pipeline=productionPipelineStateI5(entityGameId,{revisionId,language,structureStatus});
  const density=String(base.visual?.requestedDensity||"RICH").toUpperCase(),vars=pipeline?.images?.variables||[],required=vars.filter(v=>v.required),resolved=vars.filter(v=>v.binding?.asset&&v.currentMatch?.eligible),unresolvedRequired=required.filter(v=>!v.binding?.asset||!v.currentMatch?.eligible),hero=vars.find(v=>v.variableKey==="IMAGE:HERO"),heroResolved=Boolean(hero?.binding?.asset&&hero?.currentMatch?.eligible),diversity=pipeline?.images?.diversity||{pass:false,score:0,excessiveReuse:[]},gap=pipeline?.composition?.visualGap||{score:0,totalSections:0,groundedSections:0,maxConsecutiveUngrounded:0},preview=latestPreviewSnapshotI5(entityGameId,{revisionId,language,structureStatus}),quality=researchQualitySummary(entityGameId,{buildId,revisionId});
  const requiredCoverage=required.length?(required.length-unresolvedRequired.length)/required.length:0,sectionCoverage=gap.totalSections?gap.groundedSections/gap.totalSections:0,semanticAverage=resolved.length?resolved.reduce((n,v)=>n+Number(v.currentMatch?.totalScore||0),0)/resolved.length:0,baseCoverage=Number(base.visual?.coverageScore||0),visualScore=Math.max(0,Math.min(100,Math.round(baseCoverage*.16+requiredCoverage*100*.28+sectionCoverage*100*.24+diversity.score*.16+semanticAverage*.16))),target=density==="IMMERSIVE"?88:density==="RICH"?80:density==="BALANCED"?65:45;
  const blockers=[...(base.blockers||[])].filter(x=>!["VISUAL_COVERAGE_BELOW_DENSITY_MINIMUM","VISUAL_COVERAGE_BELOW_I4_TARGET","VISUAL_GAP_TOO_HIGH","REQUIRED_IMAGE_VARIABLES_UNRESOLVED","PREVIEW_REQUIRED","PREVIEW_STALE","LOW_RESOLVED_ASSET_DIVERSITY"].includes(x.code)),warnings=[...(base.warnings||[])].filter(x=>x.code!=="LOW_RESOLVED_ASSET_DIVERSITY");
  if(!vars.length)blockers.push(issue("IMAGE_VARIABLES_MISSING","Content has not declared its visual needs yet."));
  if(["RICH","IMMERSIVE"].includes(density)&&!heroResolved)blockers.push(issue("HERO_RESOLVED_REQUIRED","The main image still needs a high-confidence game-specific asset.","BLOCKER",{variableId:hero?.id||null}));
  if(unresolvedRequired.length)blockers.push(issue("REQUIRED_IMAGES_RESOLVED_REQUIRED",`${unresolvedRequired.length} required visual(s) still need an appropriate approved image.`,"BLOCKER",{variables:unresolvedRequired.map(v=>({id:v.id,label:v.label}))}));
  if(["RICH","IMMERSIVE"].includes(density)&&!diversity.pass)blockers.push(issue("ASSET_DIVERSITY_REQUIRED","The page needs more visual variety; too few unique game assets are carrying too many sections.","BLOCKER",diversity));
  if(diversity.excessiveReuse?.length)blockers.push(issue("EXCESSIVE_ASSET_REUSE","One or more images are reused too often as primary section visuals.","BLOCKER",{assets:diversity.excessiveReuse}));
  if(resolved.some(v=>Number(v.currentMatch?.semanticMatch||0)<35||Number(v.currentMatch?.roleMatch||0)<45))blockers.push(issue("SEMANTIC_IMAGE_MATCH_REQUIRED","One or more selected images do not match the visual need of their section."));
  if(visualScore<target)blockers.push(issue("VISUAL_COVERAGE_BELOW_I5_TARGET",`The page visual quality is ${visualScore}%, below the ${density} target of ${target}%.`));
  if(["RICH","IMMERSIVE"].includes(density)&&gap.totalSections&&gap.score<75)blockers.push(issue("VISUAL_GAP_AUTO_HEAL_REQUIRED",`The page still has long visually empty areas (visual continuity ${gap.score}%).`,"BLOCKER",{maxConsecutiveUngrounded:gap.maxConsecutiveUngrounded}));
  if(!preview)blockers.push(issue("PREVIEW_REQUIRED","Generate the preview before publishing."));else if(preview.status!=="READY")blockers.push(issue("PREVIEW_CURRENT_REQUIRED","Preview needs updating before publishing.","BLOCKER",{status:preview.status}));
  if(quality.rejected>0)warnings.push(issue("RESEARCH_CONTENT_FILTERED",`${quality.rejected} low-quality or boilerplate research fragment(s) were rejected before page composition.`,"WARNING",quality));
  if(quality.usefulFacts===0&&buildId)blockers.push(issue("USEFUL_RESEARCH_REQUIRED","Research did not produce enough useful game-specific facts for this build."));
  const domains={...base.domains,RESEARCH_STATUS:quality.usefulFacts>0||!buildId?base.domains?.RESEARCH_STATUS||"READY":"PARTIAL",CONTENT_STATUS:base.domains?.CONTENT_STATUS||"READY",IMAGES_STATUS:!vars.length?"FAILED":unresolvedRequired.length?"PARTIAL":"READY",VISUAL_GROUNDING_STATUS:visualScore>=target&&heroResolved&&diversity.pass&&!unresolvedRequired.length?"VALIDATED":"INCOMPLETE",PREVIEW_STATUS:preview?.status||"NOT_STARTED",PUBLICATION_STATUS:blockers.length?"BLOCKED":"READY"};
  const stages={RESEARCH_CONTENT:{status:domains.CONTENT_STATUS,metrics:{usefulFacts:quality.usefulFacts,rejected:quality.rejected,boilerplateRejected:quality.boilerplateRejected,topicsSupported:quality.topicsSupported}},IMAGES:{status:domains.IMAGES_STATUS,metrics:{total:vars.length,resolved:resolved.length,required:required.length,unresolvedRequired:unresolvedRequired.length,diversityScore:diversity.score}},APPEARANCE:{status:visualScore>=target?"READY":"PARTIAL",metrics:{visualQuality:visualScore,target,visualGap:gap.score,diversity:diversity.score}},PREVIEW:{status:domains.PREVIEW_STATUS,metrics:{snapshotId:preview?.id||null}},PUBLICATION:{status:domains.PUBLICATION_STATUS,metrics:{blockers:blockers.length,warnings:warnings.length}}};
  if(persist)for(const [stageKey,value] of Object.entries(stages))setBuilderStage(entityGameId,revisionId,stageKey,{...value,message:stageKey==="PUBLICATION"?(blockers.length?"Cannot publish yet. Open the simple checklist or use Fix Automatically.":"Ready for explicit publication."):""});
  return {version:"0.99-I5",publicVersion:"0.99",entityGameId,revisionId:revisionId||null,domains,research:{...base.research,quality},content:base.content,images:{total:vars.length,required:required.length,resolved:resolved.length,unresolvedRequired:unresolvedRequired.length,heroResolved,diversity,variables:vars},media:base.media,visual:{...base.visual,baseCoverageScore:baseCoverage,coverageScore:visualScore,target,requiredCoverage:Math.round(requiredCoverage*100),sectionCoverage:Math.round(sectionCoverage*100),semanticAverage:Math.round(semanticAverage),visualGap:gap,diversity},interactions:base.interactions,preview,composition:pipeline?.composition||{},stages,blockers:uniq(blockers),warnings:uniq(warnings),publicationAllowed:blockers.length===0,validatedAt:nowIso()};
}

export function assertPublicationAllowedI5(entityGameId,options={}){const validation=evaluateBuilderValidationI5(entityGameId,options);if(!validation.publicationAllowed)throw Object.assign(new Error("PUBLICATION_BLOCKED_I5"),{code:"PUBLICATION_BLOCKED_I5",validation});return validation;}
export function finalBuilderReportI5(entityGameId,options={}){const v=evaluateBuilderValidationI5(entityGameId,options),p=productionPipelineStateI5(entityGameId,options);return {version:"0.99-I5",publicVersion:"0.99",entity:p?.entity||null,summary:{research:v.domains.RESEARCH_STATUS,content:v.domains.CONTENT_STATUS,images:v.domains.IMAGES_STATUS,appearance:v.domains.VISUAL_GROUNDING_STATUS,interactions:v.domains.INTERACTION_STATUS,preview:v.domains.PREVIEW_STATUS,performance:v.domains.PERFORMANCE_STATUS,publication:v.domains.PUBLICATION_STATUS},metrics:{usefulFacts:v.research?.quality?.usefulFacts||0,rejectedResearch:v.research?.quality?.rejected||0,pages:v.content?.pages||0,sections:v.content?.sections||0,imageVariables:v.images.total,imageVariablesResolved:v.images.resolved,heroResolved:v.images.heroResolved,assetDiversity:Number(v.images.diversity?.score||0),visualQuality:Number(v.visual?.coverageScore||0),visualGapQuality:Number(v.visual?.visualGap?.score||0),interactions:v.interactions?.totalPersisted||0},blockers:v.blockers,warnings:v.warnings,plainChecklist:v.blockers.map(b=>b.message),technical:{stages:p?.stages||[],previewId:v.preview?.id||null,revisionId:v.revisionId},generatedAt:nowIso()};}
