import { createHash, randomBytes, randomUUID, scryptSync, timingSafeEqual } from "node:crypto";
import { createUser, createSession, deleteSession, deleteSessionsForUser, getPreference, getSession, getUserByEmail, getUserCredentialsById, removeNewUser, setPreference, touchLastLogin, updatePasswordCredentials } from "../database/repositories/user-repository.mjs";
import { ensureProfile } from "../database/repositories/profile-repository.mjs";
import { entitlementSnapshot, getEffectiveTier } from "../database/repositories/entitlement-repository.mjs";
import { canUseTheme, normalizeTheme, themePublicState } from "../themes/theme-service.mjs";
import { subscriptionPublicState } from "../subscriptions/subscription-service.mjs";
import { db } from "../database/connection.mjs";

const COOKIE="gv_session";
function hashToken(token){return createHash("sha256").update(token).digest("hex");}
function hashPassword(password,salt){return scryptSync(password,salt,64).toString("hex");}
function parseCookies(req){const out={};for(const part of String(req.headers.cookie||"").split(";")){const i=part.indexOf("=");if(i<0)continue;out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim());}return out;}
function secureCookie(req){return req.secure || String(req.headers["x-forwarded-proto"]||"").split(",")[0].trim()==="https";}
function setSessionCookie(req,res,token,expiresAt){const maxAge=Math.max(0,new Date(expiresAt).getTime()-Date.now());res.cookie(COOKIE,token,{httpOnly:true,sameSite:"lax",secure:secureCookie(req),path:"/",maxAge});}
export function currentAuth(req){const token=parseCookies(req)[COOKIE];if(!token)return null;return getSession(hashToken(token));}
function publicStaffIdentity(userId,tier){try{const row=db.prepare(`SELECT role,suspended FROM staff_role_assignments WHERE user_id=?`).get(userId);if(row&&!Number(row.suspended))return {staffRole:row.role,badge:row.role,staffSuspended:false};if(row)return {staffRole:row.role,badge:tier,staffSuspended:true};}catch{}return {staffRole:"NONE",badge:tier,staffSuspended:false};}
function enriched(user){if(!user)return null;const tier=getEffectiveTier(user.id),profile=ensureProfile(user.id);return {...user,accountTier:tier,tier,...publicStaffIdentity(user.id,tier),entitlements:entitlementSnapshot(user.id),avatarUrl:profile?.avatarUrl||"",avatarDisplayUrl:profile?.avatarDisplayUrl||""};}
export function createAuthenticatedSession(req,res,user){const token=randomBytes(32).toString("base64url");const days=Math.max(1,Math.min(90,Number(process.env.GAMEVAULT_SESSION_DAYS||30)));const expiresAt=new Date(Date.now()+days*86400000).toISOString();createSession({tokenHash:hashToken(token),userId:user.id,expiresAt});setSessionCookie(req,res,token,expiresAt);const pref=getPreference(user.id);return {user:enriched(user),preferences:pref,theme:themePublicState(user.id,pref.theme),subscription:subscriptionPublicState(user.id)};}
export function register(req,res,{email,password,displayName,username}){const cleanEmail=String(email||"").trim().toLowerCase();const cleanName=String(displayName||"").trim().slice(0,60);const cleanUsername=String(username||"").trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(cleanEmail))throw new Error("Informe um e-mail válido.");if(String(password||"").length<8)throw new Error("A senha precisa ter pelo menos 8 caracteres.");if(getUserByEmail(cleanEmail))throw new Error("Já existe uma conta com este e-mail.");const salt=randomBytes(16).toString("hex");const user=createUser({id:randomUUID(),email:cleanEmail,displayName:cleanName,passwordHash:hashPassword(String(password),salt),passwordSalt:salt});try{ensureProfile(user.id,{preferredUsername:cleanUsername||null});}catch(error){removeNewUser(user.id);throw error;}return createAuthenticatedSession(req,res,user);}
export function authenticateCredentials({email,password}={}){const record=getUserByEmail(String(email||"").trim().toLowerCase());if(!record)throw new Error("E-mail ou senha incorretos.");const candidate=Buffer.from(hashPassword(String(password||""),record.passwordSalt),"hex"),expected=Buffer.from(record.passwordHash,"hex");if(candidate.length!==expected.length||!timingSafeEqual(candidate,expected))throw new Error("E-mail ou senha incorretos.");const {passwordHash,passwordSalt,...user}=record;return touchLastLogin(user.id)||user;}
export function login(req,res,input){return createAuthenticatedSession(req,res,authenticateCredentials(input));}
export function verifyUserPassword(userId,password){const record=getUserCredentialsById(String(userId||""));if(!record)return false;const candidate=Buffer.from(hashPassword(String(password||""),record.passwordSalt),"hex"),expected=Buffer.from(record.passwordHash,"hex");return candidate.length===expected.length&&timingSafeEqual(candidate,expected);}
export function changeUserPassword(userId,{currentPassword,newPassword}={}){if(!verifyUserPassword(userId,currentPassword))throw new Error("Senha atual incorreta.");if(String(newPassword||"").length<8)throw new Error("A nova senha precisa ter pelo menos 8 caracteres.");if(String(newPassword).length>256)throw new Error("A nova senha é muito longa.");const salt=randomBytes(16).toString("hex");updatePasswordCredentials(String(userId),{passwordHash:hashPassword(String(newPassword),salt),passwordSalt:salt});deleteSessionsForUser(String(userId));return true;}
export function rotateLoginSession(req,res,user){deleteSessionsForUser(user.id);return createAuthenticatedSession(req,res,user);}
export function logout(req,res){const token=parseCookies(req)[COOKIE];if(token)deleteSession(hashToken(token));res.clearCookie(COOKIE,{httpOnly:true,sameSite:"lax",secure:secureCookie(req),path:"/"});return {ok:true};}
export function authPayload(req){const session=currentAuth(req);if(!session)return {authenticated:false,user:null,preferences:null,theme:{tier:"FREE",selectedTheme:"FREE_DARK",availableThemes:[{id:"FREE_DARK",name:"Escuro"},{id:"FREE_LIGHT",name:"Claro"}],devLightSpecial:false},subscription:{subscription:{plan:"FREE",status:"ACTIVE"},tier:"FREE",entitlements:{tier:"FREE",free:true,pro:false,dev:false}}};const pref=getPreference(session.user.id);return {authenticated:true,user:enriched(session.user),preferences:pref,theme:themePublicState(session.user.id,pref.theme),subscription:subscriptionPublicState(session.user.id)};}
export function updatePreferences(req,input={}){
  const session=currentAuth(req);if(!session)throw new Error("Faça login para salvar preferências na conta.");
  const allowedLang=new Set(["pt-BR","en-US","es-ES"]);if(input.language&&!allowedLang.has(input.language))throw new Error("Idioma não suportado.");
  let nextTheme=input.theme?normalizeTheme(input.theme):undefined;if(nextTheme&&!canUseTheme(session.user.id,nextTheme))throw new Error("Este tema não está disponível para o seu nível de conta.");
  const responseLengths=new Set(["SHORT","BALANCED","DETAILED"]),answerLangs=new Set(["AUTO","PT-BR","EN","ES"]),densities=new Set(["COMFORTABLE","COMPACT"]),animations=new Set(["ON","REDUCED","OFF"]),visibility=new Set(["PUBLIC","FRIENDS","PRIVATE"]);
  if(input.responseLength&&!responseLengths.has(String(input.responseLength).toUpperCase()))throw new Error("Tamanho de resposta inválido.");
  if(input.answerLanguage&&!answerLangs.has(String(input.answerLanguage).toUpperCase()))throw new Error("Idioma de resposta inválido.");
  if(input.interfaceDensity&&!densities.has(String(input.interfaceDensity).toUpperCase()))throw new Error("Densidade de interface inválida.");
  if(input.animations&&!animations.has(String(input.animations).toUpperCase()))throw new Error("Preferência de animações inválida.");
  if(input.profileVisibility&&!visibility.has(String(input.profileVisibility).toUpperCase()))throw new Error("Visibilidade de perfil inválida.");
  if(input.activityVisibility&&!visibility.has(String(input.activityVisibility).toUpperCase()))throw new Error("Visibilidade de atividade inválida.");
  if(input.uiScale!==undefined){const n=Number(input.uiScale);if(!Number.isFinite(n)||n<.85||n>1.3)throw new Error("Escala da interface inválida.");}
  if(input.experimental!==undefined&&getEffectiveTier(session.user.id)!=="DEV")throw new Error("Configurações experimentais exigem DEV.");
  const clean={...input,theme:nextTheme};for(const k of ["responseLength","answerLanguage","interfaceDensity","animations","profileVisibility","activityVisibility"])if(clean[k]!==undefined)clean[k]=String(clean[k]).toUpperCase();const preferences=setPreference(session.user.id,clean);return {...preferences,tier:getEffectiveTier(session.user.id),themeState:themePublicState(session.user.id,preferences.theme)};
}
