// Trusted product routes. Client-provided role/theme values never enter this map.
const text={
 'pt-BR':{catalog:'Explore os jogos pelo catálogo. Abra uma página para ver história, personagens, guias e informações disponíveis.',profile:'Abra seu perfil para ver favoritos e jogos seguidos. Em Configurar perfil você pode escolher um avatar e editar sua apresentação.',language:'Abra Línguas para escolher português, inglês ou espanhol. A interface muda na hora; o idioma das respostas pode ser ajustado nas configurações.',music:'Use o controle de música no cabeçalho para reproduzir, pausar ou ajustar o volume. O navegador pode exigir um primeiro clique para liberar o áudio.',media:'No Image Manager, selecione o jogo e o destino: capa, logo ou banner. Ajuste o enquadramento, confirme e salve. A capa do catálogo e o logo da página são independentes.',cinematic:'No Cinematic Lab, selecione a animação junto à prévia e use Reproduzir, Pausar ou Reiniciar. O contexto e os ajustes adicionais ficam nas opções avançadas.',builder:'No Universe Builder, selecione o jogo, prepare o conteúdo e revise a prévia antes de salvar. Aprimorar usa as fontes disponíveis para enriquecer as seções.',social:'No Social você pode encontrar amigos, participar de comunidades e conversar. Entre na conta para publicar e enviar mensagens.',denied:'Esta ferramenta não está disponível para a sua conta. Você pode consultar jogos e usar as funções públicas.',help:'Posso ajudar a explorar um jogo ou encontrar uma função do GameIndex. Diga o nome do jogo ou a tarefa que quer realizar.',open:'Abrir',source:'Catálogo GameIndex',developer:'Desenvolvedor',publisher:'Publicadora',release:'Lançamento original registrado',platforms:'Plataformas registradas',genres:'Gêneros',overview:'Visão geral',record:'Informações do catálogo; disponibilidade e atualizações recentes precisam de confirmação.'},
 'en-US':{catalog:'Browse the games catalog. Open a game page for its story, characters, guides and available information.',profile:'Open your profile to see favorites and followed games. Profile settings let you choose an avatar and edit your bio.',language:'Open Languages to choose Portuguese, English or Spanish. The interface changes immediately; answer language is available in settings.',music:'Use the music control in the header to play, pause or adjust volume. Your browser may require a first click to allow audio.',media:'In Image Manager, select a game and a destination: cover, logo or banner. Adjust framing, confirm and save. Catalog covers and page logos are independent.',cinematic:'In Cinematic Lab, select an animation beside its preview and use Play, Pause or Restart. Context and additional controls are in advanced options.',builder:'In Universe Builder, select a game, prepare content and review the preview before saving. Enhance uses available sources to enrich sections.',social:'Use Social to find friends, join communities and chat. Sign in to publish and send messages.',denied:'This tool is not available for your account. You can browse games and use public features.',help:'I can help you explore a game or find a GameIndex feature. Name the game or describe your task.',open:'Open',source:'GameIndex catalog',developer:'Developer',publisher:'Publisher',release:'Recorded original release',platforms:'Recorded platforms',genres:'Genres',overview:'Overview',record:'Catalog information; current availability and recent updates require verification.'},
 'es-ES':{catalog:'Explora el catálogo de juegos. Abre una página para ver historia, personajes, guías e información disponible.',profile:'Abre tu perfil para ver favoritos y juegos seguidos. En Configurar perfil puedes elegir un avatar y editar tu biografía.',language:'Abre Idiomas para elegir portugués, inglés o español. La interfaz cambia al instante; el idioma de las respuestas se ajusta en Configuración.',music:'Usa el control de música del encabezado para reproducir, pausar o ajustar el volumen. El navegador puede necesitar un primer clic para permitir audio.',media:'En Image Manager, selecciona el juego y el destino: portada, logo o banner. Ajusta el encuadre, confirma y guarda. La portada del catálogo y el logo son independientes.',cinematic:'En Cinematic Lab, selecciona una animación junto a la vista previa y usa Reproducir, Pausar o Reiniciar. El contexto y los ajustes adicionales están en opciones avanzadas.',builder:'En Universe Builder, selecciona el juego, prepara el contenido y revisa la vista previa antes de guardar. Mejorar utiliza las fuentes disponibles para ampliar las secciones.',social:'En Social puedes encontrar amigos, unirte a comunidades y conversar. Inicia sesión para publicar y enviar mensajes.',denied:'Esta herramienta no está disponible para tu cuenta. Puedes consultar juegos y usar las funciones públicas.',help:'Puedo ayudarte a explorar un juego o encontrar una función de GameIndex. Indica el juego o la tarea que quieres realizar.',open:'Abrir',source:'Catálogo GameIndex',developer:'Desarrollador',publisher:'Distribuidora',release:'Lanzamiento original registrado',platforms:'Plataformas registradas',genres:'Géneros',overview:'Resumen',record:'Información del catálogo; la disponibilidad y las novedades necesitan confirmación.'}
};
const normalize=q=>String(q||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const routes=[
 ['media',/image manager|gerenciador de imag|gestor de imag|enquadr|capa.*(?:salvar|editar|alterar)|(?:logo|banner).*(?:trocar|editar|change)/,'/image-library.html','Image Manager','image_management'],
 ['cinematic',/cinematic lab|cutscene|cutcene|testar.*anim|test.*animation/,'/cinematic-test-lab.html','Cinematic Lab','cinematic_test'],
 ['builder',/universe builder|gerar.*(?:universo|pagina)|generate.*page/,'/universe-builder.html','Universe Builder','universe_build'],
 ['language',/idioma|lingua|language|traduz.*interface|translate.*interface/,'/languages.html','Línguas'],
 ['profile',/meu perfil|my profile|mi perfil|avatar|foto de perfil/,'/profile-settings.html','Configurar perfil'],
 ['music',/musica.*(?:site|gameindex|lobby|ativ|tocar)|music.*(?:gameindex|lobby|play)|volume|sem som/,'/settings.html','Configurações'],
 ['social',/como.*(?:amigos|comunidade|mensage)|how.*(?:friends|communit|message)|social.*gameindex/,'/social.html','Social'],
 ['catalog',/catalogo|catalog|como.*(?:buscar|encontrar).*jog|how.*find.*game/,'/games.html','Games']
];
export function productAnswer(question,language,capabilities=[]){
 const q=normalize(question),c=text[language]||text['pt-BR'];
 const route=routes.find(([,pattern])=>pattern.test(q));
 if(!route){if(!/^(?:oi|ola|hello|hi|hola)[!.? ]*$/.test(q)&&!/(?:o que|what|que) (?:voce|you|podes|puedes).*(?:faz|do|hacer)|ajuda.*gameindex|help.*gameindex/.test(q))return null;return {directAnswer:c.help,details:[],sources:[],actions:[{label:'Games',href:'/games.html'}],canRetry:false};}
 const [key,,,label,cap]=route,allowed=!cap||capabilities.includes(cap);
 return {directAnswer:allowed?c[key]:c.denied,details:[],sources:[],actions:allowed?[{label,href:route[2]}]:[{label:'Games',href:'/games.html'}],canRetry:false};
}
export function catalogAnswer(game,question,language){
 if(!game)return null;
 const c=text[language]||text['pt-BR'],q=normalize(question),rows=[];
 const add=(key,value)=>{if(value)rows.push(`${c[key]}: ${Array.isArray(value)?value.join(', '):value}.`);};
 if(/desenvolv|developer|developed|criou|created|creo|desarroll|quem fez/.test(q))add('developer',game.developer);
 if(/publicadora|publisher|publish|distribuid/.test(q))add('publisher',game.publisher);
 if(/lancamento|lancou|release|released|lanzo|lanzamiento|saiu/.test(q)&&!/atual|hoje|latest|current|next|proxim/.test(q))add('release',game.releaseDate);
 if(/plataforma|platform|onde.*jogar|where.*play|donde.*jugar/.test(q))add('platforms',game.platforms);
 if(/genero|genre|tipo de jogo|type of game/.test(q))add('genres',game.genres);
 if(!rows.length)return null;
 return {directAnswer:`${game.name} — ${rows.shift()}`,details:rows,sources:[{title:c.source,url:`/game.html?slug=${encodeURIComponent(game.slug)}`}],notice:c.record,confidence:.85,canRetry:false,actions:[{label:game.name,href:`/game.html?slug=${encodeURIComponent(game.slug)}`} ]};
}
